// === Level 10 完整清單 (依據圖片 164658 ~ 164734 整理，共約 230 字) ===
    { "level": 10, "word": "abroad", "syllables": ["a", "broad"], "ipa": "/əˈbrɔːd/", "meaning": "adv. 在國外" },
    { "level": 10, "word": "accompany", "syllables": ["ac", "com", "pa", "ny"], "ipa": "/əˈkʌmpəni/", "meaning": "v. 陪同、伴隨" },
    { "level": 10, "word": "account", "syllables": ["ac", "count"], "ipa": "/əˈkaʊnt/", "meaning": "n. 帳、帳目" },
    { "level": 10, "word": "accountant", "syllables": ["ac", "coun", "tant"], "ipa": "/əˈkaʊntənt/", "meaning": "n. 會計師；會計人" },
    { "level": 10, "word": "action", "syllables": ["ac", "tion"], "ipa": "/ˈækʃn/", "meaning": "n. 動作" },
    { "level": 10, "word": "actually", "syllables": ["ac", "tu", "al", "ly"], "ipa": "/ˈæktʃuəli/", "meaning": "adv. 事實上" },
    { "level": 10, "word": "admire", "syllables": ["ad", "mire"], "ipa": "/ədˈmaɪər/", "meaning": "v. 欽佩、仰慕" },
    { "level": 10, "word": "advantage", "syllables": ["ad", "van", "tage"], "ipa": "/ədˈvæntɪdʒ/", "meaning": "n. 優勢、利益" },
    { "level": 10, "word": "advertisement", "syllables": ["ad", "ver", "tise", "ment"], "ipa": "/ˌædvərˈtaɪzmənt/", "meaning": "n. 廣告" },
    { "level": 10, "word": "advise", "syllables": ["ad", "vise"], "ipa": "/ədˈvaɪz/", "meaning": "v. 勸告、建議" },
    { "level": 10, "word": "affect", "syllables": ["af", "fect"], "ipa": "/əˈfekt/", "meaning": "v. 影響；假裝" },
    { "level": 10, "word": "afterword", "syllables": ["af", "ter", "word"], "ipa": "/ˈæftərwɜːrd/", "meaning": "n. 跋；後記" },
    { "level": 10, "word": "air-conditioned", "syllables": ["air", "con", "di", "tioned"], "ipa": "/ˌer kənˈdɪʃənd/", "meaning": "adj. 裝有空氣調節設備的" },
    { "level": 10, "word": "angle", "syllables": ["an", "gle"], "ipa": "/ˈæŋɡl/", "meaning": "n. 角；角度" },
    { "level": 10, "word": "anyhow", "syllables": ["an", "y", "how"], "ipa": "/ˈenhaʊ/", "meaning": "adj. 無論如何" },
    { "level": 10, "word": "anytime", "syllables": ["an", "y", "time"], "ipa": "/ˈenitaɪm/", "meaning": "adj. 在任何時候" },
    { "level": 10, "word": "apologize", "syllables": ["a", "pol", "o", "gize"], "ipa": "/əˈpɑːlədʒaɪz/", "meaning": "v. 道歉" },
    { "level": 10, "word": "appoint", "syllables": ["ap", "point"], "ipa": "/əˈpɔɪnt/", "meaning": "v. 任命" },
    { "level": 10, "word": "appointment", "syllables": ["ap", "point", "ment"], "ipa": "/əˈpɔɪntmənt/", "meaning": "v. 任命" },
    { "level": 10, "word": "aquarium", "syllables": ["a", "quar", "i", "um"], "ipa": "/əˈkweriəm/", "meaning": "n. 養魚缸" },
    { "level": 10, "word": "area", "syllables": ["ar", "ea"], "ipa": "/ˈeriə/", "meaning": "n. 地區" },
    { "level": 10, "word": "argument", "syllables": ["ar", "gu", "ment"], "ipa": "/ˈɑːrɡjumənt/", "meaning": "n. 爭執" },
    { "level": 10, "word": "army", "syllables": ["ar", "my"], "ipa": "/ˈɑːrmi/", "meaning": "n. 軍隊" },
    { "level": 10, "word": "arrival", "syllables": ["ar", "ri", "val"], "ipa": "/əˈraɪvl/", "meaning": "n. 到達" },
    { "level": 10, "word": "article", "syllables": ["ar", "ti", "cle"], "ipa": "/ˈɑːrtɪkl/", "meaning": "n. 文章" },
    { "level": 10, "word": "ash", "syllables": ["ash"], "ipa": "/æʃ/", "meaning": "n. 灰燼" },
    { "level": 10, "word": "aspirin", "syllables": ["as", "pi", "rin"], "ipa": "/ˈæsprɪn/", "meaning": "n. 阿斯匹靈" },
    { "level": 10, "word": "assist", "syllables": ["as", "sist"], "ipa": "/əˈsɪst/", "meaning": "v. 幫助" },
    { "level": 10, "word": "assistance", "syllables": ["as", "sis", "tance"], "ipa": "/əˈsɪstəns/", "meaning": "n. 幫助" },
    { "level": 10, "word": "athletic", "syllables": ["ath", "let", "ic"], "ipa": "/æθˈletɪk/", "meaning": "adj. 運動的" },
    { "level": 10, "word": "attract", "syllables": ["at", "tract"], "ipa": "/əˈtrækt/", "meaning": "adj. 吸；吸引" },
    { "level": 10, "word": "attraction", "syllables": ["at", "trac", "tion"], "ipa": "/əˈtrækʃn/", "meaning": "n. 吸引；吸引力" },
    { "level": 10, "word": "attractive", "syllables": ["at", "trac", "tive"], "ipa": "/əˈtræktɪv/", "meaning": "adj. 有吸引力的" },
    { "level": 10, "word": "audio", "syllables": ["au", "di", "o"], "ipa": "/ˈɔːdioʊ/", "meaning": "n.adj. 聽覺的、音響裝置" },
    { "level": 10, "word": "author", "syllables": ["au", "thor"], "ipa": "/ˈɔːθər/", "meaning": "n.v. 作者、著作" },
    { "level": 10, "word": "autobiography", "syllables": ["au", "to", "bi", "og", "ra", "phy"], "ipa": "/ˌɔːtəbaɪˈɑːɡrəfi/", "meaning": "n. 自傳" },
    { "level": 10, "word": "automobile", "syllables": ["au", "to", "mo", "bile"], "ipa": "/ˌɔːtəməˈbiːl/", "meaning": "n.adj. 汽車" },
    { "level": 10, "word": "available", "syllables": ["a", "vail", "a", "ble"], "ipa": "/əˈveɪləbl/", "meaning": "adj. 有空的；可使用的" },
    { "level": 10, "word": "awake", "syllables": ["a", "wake"], "ipa": "/əˈweɪk/", "meaning": "v. 喚醒" },
    { "level": 10, "word": "awful", "syllables": ["aw", "ful"], "ipa": "/ˈɔːfl/", "meaning": "adj. 可怕的" },
    { "level": 10, "word": "B.C.", "syllables": ["B.C."], "ipa": "/ˌbiː ˈsiː/", "meaning": "abbr. 西元前...年" },
    { "level": 10, "word": "baby-sit", "syllables": ["ba", "by", "sit"], "ipa": "/ˈbeɪbisɪt/", "meaning": "v. 當臨時保姆" },
    { "level": 10, "word": "babysitter", "syllables": ["ba", "by", "sit", "ter"], "ipa": "/ˈbeɪbisɪtər/", "meaning": "n. 代人照看孩子者" },
    { "level": 10, "word": "background", "syllables": ["back", "ground"], "ipa": "/ˈbækɡraʊnd/", "meaning": "n. 背景" },
    { "level": 10, "word": "backward", "syllables": ["back", "ward"], "ipa": "/ˈbækwərd/", "meaning": "adv.adj. 向後的" },
    { "level": 10, "word": "bacon", "syllables": ["ba", "con"], "ipa": "/ˈbeɪkən/", "meaning": "n. 燻豬肉" },
    { "level": 10, "word": "badly", "syllables": ["bad", "ly"], "ipa": "/ˈbædli/", "meaning": "adv. 壞；拙劣地" },
    { "level": 10, "word": "baggage", "syllables": ["bag", "gage"], "ipa": "/ˈbæɡɪdʒ/", "meaning": "n. 行李" },
    { "level": 10, "word": "balance", "syllables": ["bal", "ance"], "ipa": "/ˈbæləns/", "meaning": "n. 平衡" },
    { "level": 10, "word": "bamboo", "syllables": ["bam", "boo"], "ipa": "/ˌbæmˈbuː/", "meaning": "n. 竹子" },
    { "level": 10, "word": "battery", "syllables": ["bat", "ter", "y"], "ipa": "/ˈbætəri/", "meaning": "n. 電池" },
    { "level": 10, "word": "beauty", "syllables": ["beau", "ty"], "ipa": "/ˈbjuːti/", "meaning": "n. 美、美麗" },
    { "level": 10, "word": "belief", "syllables": ["be", "lief"], "ipa": "/bɪˈliːf/", "meaning": "n. 信念" },
    { "level": 10, "word": "bet", "syllables": ["bet"], "ipa": "/bet/", "meaning": "n.v. 打賭" },
    { "level": 10, "word": "bike", "syllables": ["bike"], "ipa": "/baɪk/", "meaning": "n.v. 腳踏車" },
    { "level": 10, "word": "bingo", "syllables": ["bin", "go"], "ipa": "/ˈbɪŋɡoʊ/", "meaning": "n. 賓果遊戲" },
    { "level": 10, "word": "biscuit", "syllables": ["bis", "cuit"], "ipa": "/ˈbɪskɪt/", "meaning": "n. 小麵包" },
    { "level": 10, "word": "book store", "syllables": ["book", "store"], "ipa": "/ˈbʊkstɔːr/", "meaning": "n. 書局" },
    { "level": 10, "word": "bookshelf", "syllables": ["book", "shelf"], "ipa": "/ˈbʊkʃelf/", "meaning": "n. 書架" },
    { "level": 10, "word": "boyfriend", "syllables": ["boy", "friend"], "ipa": "/ˈbɔɪfrend/", "meaning": "n. 男朋友" },
    { "level": 10, "word": "brief", "syllables": ["brief"], "ipa": "/briːf/", "meaning": "adj. 簡略的" },
    { "level": 10, "word": "briefcase", "syllables": ["brief", "case"], "ipa": "/ˈbriːfkeɪs/", "meaning": "n. 公事包" },
    { "level": 10, "word": "bull", "syllables": ["bull"], "ipa": "/bʊl/", "meaning": "n. 公牛" },
    { "level": 10, "word": "bullet", "syllables": ["bul", "let"], "ipa": "/ˈbʊlɪt/", "meaning": "n. 子彈" },
    { "level": 10, "word": "burger", "syllables": ["bur", "ger"], "ipa": "/ˈbɜːrɡər/", "meaning": "n. 漢堡牛肉餅" },
    { "level": 10, "word": "cafe", "syllables": ["ca", "fe"], "ipa": "/kæˈfeɪ/", "meaning": "n. 咖啡廳" },
    { "level": 10, "word": "calculate", "syllables": ["cal", "cu", "late"], "ipa": "/ˈkælkjuleɪt/", "meaning": "v. 計算" },
    { "level": 10, "word": "calculating", "syllables": ["cal", "cu", "lat", "ing"], "ipa": "/ˈkælkjuleɪtɪŋ/", "meaning": "adj. 計算的" },
    { "level": 10, "word": "calculator", "syllables": ["cal", "cu", "la", "tor"], "ipa": "/ˈkælkjuleɪtər/", "meaning": "n. 計算者" },
    { "level": 10, "word": "camel", "syllables": ["cam", "el"], "ipa": "/ˈkæml/", "meaning": "ph. (野)營地" },
    { "level": 10, "word": "camping", "syllables": ["camp", "ing"], "ipa": "/ˈkæmpɪŋ/", "meaning": "n. 駱駝" },
    { "level": 10, "word": "cashier", "syllables": ["cash", "ier"], "ipa": "/kæˈʃɪr/", "meaning": "n. 出納" },
    { "level": 10, "word": "catalog", "syllables": ["cat", "a", "log"], "ipa": "/ˈkætəlɔːɡ/", "meaning": "n,v. 目錄、為...編目" },
    { "level": 10, "word": "celebration", "syllables": ["cel", "e", "bra", "tion"], "ipa": "/ˌselɪˈbreɪʃn/", "meaning": "n. 慶祝" },
    { "level": 10, "word": "champion", "syllables": ["cham", "pi", "on"], "ipa": "/ˈtʃæmpiən/", "meaning": "n. 優勝者、冠軍" },
    { "level": 10, "word": "charge", "syllables": ["charge"], "ipa": "/tʃɑːrdʒ/", "meaning": "n.v. 索價、價格" },
    { "level": 10, "word": "chat", "syllables": ["chat"], "ipa": "/tʃæt/", "meaning": "n.v. 閒談" },
    { "level": 10, "word": "check", "syllables": ["check"], "ipa": "/tʃek/", "meaning": "n.v. 檢查" },
    { "level": 10, "word": "chemistry", "syllables": ["chem", "is", "try"], "ipa": "/ˈkemɪstri/", "meaning": "n. 化學" },
    { "level": 10, "word": "cherry", "syllables": ["cher", "ry"], "ipa": "/ˈtʃeri/", "meaning": "n,adj. 櫻桃、櫻桃口味的" },
    { "level": 10, "word": "cigarette", "syllables": ["cig", "a", "rette"], "ipa": "/ˈsɪɡəret/", "meaning": "n. 雪茄煙" },
    { "level": 10, "word": "cinema", "syllables": ["cin", "e", "ma"], "ipa": "/ˈsɪnəmə/", "meaning": "n. 電影院" },
    { "level": 10, "word": "circus", "syllables": ["cir", "cus"], "ipa": "/ˈsɜːrkəs/", "meaning": "n. 馬戲團；馬戲表演" },
    { "level": 10, "word": "classroom", "syllables": ["class", "room"], "ipa": "/ˈklæsruːm/", "meaning": "n. 教室" },
    { "level": 10, "word": "clinic", "syllables": ["clin", "ic"], "ipa": "/ˈklɪnɪk/", "meaning": "n. 診所、門診所" },
    { "level": 10, "word": "cloth", "syllables": ["cloth"], "ipa": "/klɔːθ/", "meaning": "n. 布；衣料" },
    { "level": 10, "word": "clothing", "syllables": ["cloth", "ing"], "ipa": "/ˈkloʊðɪŋ/", "meaning": "n. 衣服、衣著" },
    { "level": 10, "word": "cocktail", "syllables": ["cock", "tail"], "ipa": "/ˈkɑːkteɪl/", "meaning": "n. 雞尾酒" },
    { "level": 10, "word": "coconut", "syllables": ["co", "co", "nut"], "ipa": "/ˈkoʊkənʌt/", "meaning": "n. 椰子；椰肉" },
    { "level": 10, "word": "colored", "syllables": ["col", "ored"], "ipa": "/ˈkʌlərd/", "meaning": "adj. 有顏色的、彩色的" },
    { "level": 10, "word": "concern", "syllables": ["con", "cern"], "ipa": "/kənˈsɜːrn/", "meaning": "n.v. 關心" },
    { "level": 10, "word": "connect", "syllables": ["con", "nect"], "ipa": "/kəˈnekt/", "meaning": "v. 連接、連結" },
    { "level": 10, "word": "consider", "syllables": ["con", "sid", "er"], "ipa": "/kənˈsɪdər/", "meaning": "v. 考慮" },
    { "level": 10, "word": "contain", "syllables": ["con", "tain"], "ipa": "/kənˈteɪn/", "meaning": "v. 包含" },
    { "level": 10, "word": "contract", "syllables": ["con", "tract"], "ipa": "/ˈkɑːntrækt/", "meaning": "n,v. 契約" },
    { "level": 10, "word": "cooking", "syllables": ["cook", "ing"], "ipa": "/ˈkʊkɪŋ/", "meaning": "n.adj. 烹調、烹調用的" },
    { "level": 10, "word": "course", "syllables": ["course"], "ipa": "/kɔːrs/", "meaning": "n. 程序；課程" },
    { "level": 10, "word": "crawl", "syllables": ["crawl"], "ipa": "/krɔːl/", "meaning": "v. 爬、爬行" },
    { "level": 10, "word": "crime", "syllables": ["crime"], "ipa": "/kraɪm/", "meaning": "n. 犯罪" },
    { "level": 10, "word": "crossroad", "syllables": ["cross", "road"], "ipa": "/ˈkrɔːsroʊd/", "meaning": "n. 交叉路；支道" },
    { "level": 10, "word": "cruel", "syllables": ["cru", "el"], "ipa": "/ˈkruːəl/", "meaning": "adj. 殘酷的" },
    { "level": 10, "word": "dancer", "syllables": ["dan", "cer"], "ipa": "/ˈdænsər/", "meaning": "n. 跳舞者、舞蹈演員" },
    { "level": 10, "word": "dancing", "syllables": ["dan", "cing"], "ipa": "/ˈdænsɪŋ/", "meaning": "n. 跳舞" },
    { "level": 10, "word": "dawn", "syllables": ["dawn"], "ipa": "/dɔːn/", "meaning": "n,v. 破曉" },
    { "level": 10, "word": "deal", "syllables": ["deal"], "ipa": "/diːl/", "meaning": "v.n. 處理；交易；發牌" },
    { "level": 10, "word": "debate", "syllables": ["de", "bate"], "ipa": "/dɪˈbeɪt/", "meaning": "n.v. 辯論" },
    { "level": 10, "word": "democracy", "syllables": ["de", "moc", "ra", "cy"], "ipa": "/dɪˈmɑːkrəsi/", "meaning": "n. 民主" },
    { "level": 10, "word": "democratic", "syllables": ["dem", "o", "crat", "ic"], "ipa": "/ˌdeməˈkrætɪk/", "meaning": "adj. 民主的" },
    { "level": 10, "word": "describe", "syllables": ["de", "scribe"], "ipa": "/dɪˈskraɪb/", "meaning": "v. 描述" },
    { "level": 10, "word": "diary", "syllables": ["di", "a", "ry"], "ipa": "/ˈdaɪəri/", "meaning": "n. 日記、日誌" },
    { "level": 10, "word": "document", "syllables": ["doc", "u", "ment"], "ipa": "/ˈdɑːkjumənt/", "meaning": "n. 檔案" },
    { "level": 10, "word": "dunk", "syllables": ["dunk"], "ipa": "/dʌŋk/", "meaning": "v. 泡、浸" },
    { "level": 10, "word": "earrings", "syllables": ["ear", "rings"], "ipa": "/ˈɪrrɪŋz/", "meaning": "n. 【海】耳索" },
    { "level": 10, "word": "earthquake", "syllables": ["earth", "quake"], "ipa": "/ˈɜːrθkweɪk/", "meaning": "n. 地震" },
    { "level": 10, "word": "easily", "syllables": ["eas", "i", "ly"], "ipa": "/ˈiːzəli/", "meaning": "adv. 容易地、輕易地" },
    { "level": 10, "word": "editor", "syllables": ["ed", "i", "tor"], "ipa": "/ˈedɪtər/", "meaning": "n. 編輯" },
    { "level": 10, "word": "effort", "syllables": ["ef", "fort"], "ipa": "/ˈefərt/", "meaning": "n. 努力" },
    { "level": 10, "word": "elbow", "syllables": ["el", "bow"], "ipa": "/ˈelboʊ/", "meaning": "n,v. 肘、用肘推" },
    { "level": 10, "word": "electronic", "syllables": ["e", "lec", "tron", "ic"], "ipa": "/ɪˌlekˈtrɑːnɪk/", "meaning": "adj. 電子的" },
    { "level": 10, "word": "elevator", "syllables": ["el", "e", "va", "tor"], "ipa": "/ˈelɪveɪtər/", "meaning": "n. 電梯、升降機" },
    { "level": 10, "word": "elsewhere", "syllables": ["else", "where"], "ipa": "/ˌelsˈwer/", "meaning": "adv. 在別處、往別處" },
    { "level": 10, "word": "embarrass", "syllables": ["em", "bar", "rass"], "ipa": "/ɪmˈbærəs/", "meaning": "v. 尷尬" },
    { "level": 10, "word": "entry", "syllables": ["en", "try"], "ipa": "/ˈentri/", "meaning": "n. 進入、入場" },
    { "level": 10, "word": "erase", "syllables": ["e", "rase"], "ipa": "/ɪˈreɪs/", "meaning": "v. 擦掉、被擦去" },
    { "level": 10, "word": "escalator", "syllables": ["es", "ca", "la", "tor"], "ipa": "/ˈeskəleɪtər/", "meaning": "n. 自動樓梯、電扶梯" },
    { "level": 10, "word": "even", "syllables": ["e", "ven"], "ipa": "/ˈiːvn/", "meaning": "adj.v. 平的、甚至、使平坦" },
    { "level": 10, "word": "express", "syllables": ["ex", "press"], "ipa": "/ɪkˈspres/", "meaning": "v.adj. 表達、快遞、快車" },
    { "level": 10, "word": "eyebrow", "syllables": ["eye", "brow"], "ipa": "/ˈaɪbraʊ/", "meaning": "n. 眉、眉毛" },
    { "level": 10, "word": "eyesight", "syllables": ["eye", "sight"], "ipa": "/ˈaɪsaɪt/", "meaning": "n. 視力、目力" },
    { "level": 10, "word": "fail", "syllables": ["fail"], "ipa": "/feɪl/", "meaning": "v. 失敗" },
    { "level": 10, "word": "FALSE", "syllables": ["FALSE"], "ipa": "/fɔːls/", "meaning": "adj. 錯誤的" },
    { "level": 10, "word": "fashion", "syllables": ["fash", "ion"], "ipa": "/ˈfæʃn/", "meaning": "n.v. 流行式樣、製作" },
    { "level": 10, "word": "fax", "syllables": ["fax"], "ipa": "/fæks/", "meaning": "n,v. 傳真機、傳真" },
    { "level": 10, "word": "fireplace", "syllables": ["fire", "place"], "ipa": "/ˈfaɪərpleɪs/", "meaning": "n. 壁爐" },
    { "level": 10, "word": "firework", "syllables": ["fire", "work"], "ipa": "/ˈfaɪərwɜːrk/", "meaning": "n. 煙火" },
    { "level": 10, "word": "fishing", "syllables": ["fish", "ing"], "ipa": "/ˈfɪʃɪŋ/", "meaning": "n. 釣魚、捕魚" },
    { "level": 10, "word": "former", "syllables": ["for", "mer"], "ipa": "/ˈfɔːrmər/", "meaning": "pron.adj. 之前的" },
    { "level": 10, "word": "freeway", "syllables": ["free", "way"], "ipa": "/ˈfriːweɪ/", "meaning": "n. 高速公路、高速幹道" },
    { "level": 10, "word": "frozen", "syllables": ["fro", "zen"], "ipa": "/ˈfroʊzn/", "meaning": "adj. 冰凍的、結冰的" },
    { "level": 10, "word": "gain", "syllables": ["gain"], "ipa": "/ɡeɪn/", "meaning": "v.n. 得到" },
    { "level": 10, "word": "gather", "syllables": ["gath", "er"], "ipa": "/ˈɡæðər/", "meaning": "v. 聚集" },
    { "level": 10, "word": "giraffe", "syllables": ["gi", "raffe"], "ipa": "/dʒəˈræf/", "meaning": "n. 長頸鹿" },
    { "level": 10, "word": "girlfriend", "syllables": ["girl", "friend"], "ipa": "/ˈɡɜːrlfrend/", "meaning": "n. 女朋友" },
    { "level": 10, "word": "glasses", "syllables": ["glass", "es"], "ipa": "/ˈɡlæsɪz/", "meaning": "n. 眼鏡" },
    { "level": 10, "word": "grammar", "syllables": ["gram", "mar"], "ipa": "/ˈɡræmər/", "meaning": "n. 語法、文法" },
    { "level": 10, "word": "grandchild", "syllables": ["grand", "child"], "ipa": "/ˈɡræntʃaɪld/", "meaning": "n. 孫子、外孫" },
    { "level": 10, "word": "grandparent", "syllables": ["grand", "par", "ent"], "ipa": "/ˈɡrænperənt/", "meaning": "n. 祖父或祖母" },
    { "level": 10, "word": "grapefruit", "syllables": ["grape", "fruit"], "ipa": "/ˈɡreɪpfruːt/", "meaning": "n. 葡萄柚" },
    { "level": 10, "word": "guard", "syllables": ["guard"], "ipa": "/ɡɑːrd/", "meaning": "n.v. 守衛" },
    { "level": 10, "word": "hallway", "syllables": ["hall", "way"], "ipa": "/ˈhɔːlweɪ/", "meaning": "n. 走廊" },
    { "level": 10, "word": "handbag", "syllables": ["hand", "bag"], "ipa": "/ˈhændbæɡ/", "meaning": "n. 手提包" },
    { "level": 10, "word": "handy", "syllables": ["hand", "y"], "ipa": "/ˈhændi/", "meaning": "adj. 方便的、有用的" },
    { "level": 10, "word": "hang", "syllables": ["hang"], "ipa": "/hæŋ/", "meaning": "v. 懸吊" },
    { "level": 10, "word": "happily", "syllables": ["hap", "pi", "ly"], "ipa": "/ˈhæpɪli/", "meaning": "adv. 高興地" },
    { "level": 10, "word": "hardware", "syllables": ["hard", "ware"], "ipa": "/ˈhɑːrdwer/", "meaning": "n. 五金器具" },
    { "level": 10, "word": "hard-working", "syllables": ["hard", "work", "ing"], "ipa": "/ˈhɑːrd wɜːrkɪŋ/", "meaning": "adj. 辛勤工作的" },
    { "level": 10, "word": "heaven", "syllables": ["heav", "en"], "ipa": "/ˈhevn/", "meaning": "n. 天堂" },
    { "level": 10, "word": "helmet", "syllables": ["hel", "met"], "ipa": "/ˈhelmɪt/", "meaning": "n. 頭盔" },
    { "level": 10, "word": "honor", "syllables": ["hon", "or"], "ipa": "/ˈɑːnər/", "meaning": "n.v. 榮譽、名譽" },
    { "level": 10, "word": "hopefully", "syllables": ["hope", "ful", "ly"], "ipa": "/ˈhoʊpfəli/", "meaning": "adv. 抱有希望地" },
    { "level": 10, "word": "host", "syllables": ["host"], "ipa": "/hoʊst/", "meaning": "n.v. 主持人、招待方" },
    { "level": 10, "word": "housekeeper", "syllables": ["house", "keep", "er"], "ipa": "/ˈhaʊskiːpər/", "meaning": "n. 管家" },
    { "level": 10, "word": "housewife", "syllables": ["house", "wife"], "ipa": "/ˈhaʊswaɪf/", "meaning": "n. 家庭婦女" },
    { "level": 10, "word": "housework", "syllables": ["house", "work"], "ipa": "/ˈhaʊswɜːrk/", "meaning": "n. 家務勞動" },
    { "level": 10, "word": "hug", "syllables": ["hug"], "ipa": "/hʌɡ/", "meaning": "n.v. 擁抱" },
    { "level": 10, "word": "humid", "syllables": ["hu", "mid"], "ipa": "/ˈhjuːmɪd/", "meaning": "adj. 潮濕的" },
    { "level": 10, "word": "ignore", "syllables": ["ig", "nore"], "ipa": "/ɪɡˈnɔːr/", "meaning": "v. 忽視" },
    { "level": 10, "word": "independent", "syllables": ["in", "de", "pen", "dent"], "ipa": "/ˌɪndɪˈpendənt/", "meaning": "adj. 獨立的" },
    { "level": 10, "word": "indoor", "syllables": ["in", "door"], "ipa": "/ˈɪndɔːr/", "meaning": "adj. 屋內的" },
    { "level": 10, "word": "indoors", "syllables": ["in", "doors"], "ipa": "/ˌɪnˈdɔːrz/", "meaning": "adv. 在屋內" },
    { "level": 10, "word": "keyboard", "syllables": ["key", "board"], "ipa": "/ˈkiːbɔːrd/", "meaning": "n. 鍵盤" },
    { "level": 10, "word": "lecture", "syllables": ["lec", "ture"], "ipa": "/ˈlektʃər/", "meaning": "n. 講課" },
    { "level": 10, "word": "lemonade", "syllables": ["lem", "on", "ade"], "ipa": "/ˌleməˈneɪd/", "meaning": "n. 檸檬水" },
    { "level": 10, "word": "leopard", "syllables": ["leop", "ard"], "ipa": "/ˈlepərd/", "meaning": "n. 豹" },
    { "level": 10, "word": "lily", "syllables": ["lil", "y"], "ipa": "/ˈlɪli/", "meaning": "n. 百合" },
    { "level": 10, "word": "lipstick", "syllables": ["lip", "stick"], "ipa": "/ˈlɪpstɪk/", "meaning": "n. 口紅、唇膏" },
    { "level": 10, "word": "nickname", "syllables": ["nick", "name"], "ipa": "/ˈnɪkneɪm/", "meaning": "n.v. 綽號、給...取綽號" },
    { "level": 10, "word": "noble", "syllables": ["no", "ble"], "ipa": "/ˈnoʊbl/", "meaning": "n. 貴族" },
    { "level": 10, "word": "northeast", "syllables": ["north", "east"], "ipa": "/ˌnɔːrθˈiːst/", "meaning": "n. 東北方" },
    { "level": 10, "word": "north-west", "syllables": ["north", "west"], "ipa": "/ˌnɔːrθˈwest/", "meaning": "n. 西北方" },
    { "level": 10, "word": "nowhere", "syllables": ["no", "where"], "ipa": "/ˈnoʊwer/", "meaning": "adv. 無處、到處都無" },
    { "level": 10, "word": "occur", "syllables": ["oc", "cur"], "ipa": "/əˈkɜːr/", "meaning": "v. 發生" },
    { "level": 10, "word": "oh", "syllables": ["oh"], "ipa": "/oʊ/", "meaning": "int. (驚叫聲)哦、哎呀" },
    { "level": 10, "word": "Olympic", "syllables": ["O", "lym", "pic"], "ipa": "/əˈlɪmpɪk/", "meaning": "n.adj. 奧林匹克的一項賽事" },
    { "level": 10, "word": "opinion", "syllables": ["o", "pin", "ion"], "ipa": "/əˈpɪnjən/", "meaning": "n. 意見" },
    { "level": 10, "word": "otherwise", "syllables": ["oth", "er", "wise"], "ipa": "/ˈʌðərwaɪz/", "meaning": "adj.adv. 另外的、另外" },
    { "level": 10, "word": "ourselves", "syllables": ["our", "selves"], "ipa": "/aʊərˈselvz/", "meaning": "pron. 我們自己" },
    { "level": 10, "word": "outdoor", "syllables": ["out", "door"], "ipa": "/ˈaʊtdɔːr/", "meaning": "adj. 室外的" },
    { "level": 10, "word": "outdoors", "syllables": ["out", "doors"], "ipa": "/ˌaʊtˈdɔːrz/", "meaning": "n. 戶外" },
    { "level": 10, "word": "oval", "syllables": ["o", "val"], "ipa": "/ˈoʊvl/", "meaning": "n. 卵形、橢圓" },
    { "level": 10, "word": "overnight", "syllables": ["o", "ver", "night"], "ipa": "/ˌoʊvərˈnaɪt/", "meaning": "adj.adv. 前一天晚上的" },
    { "level": 10, "word": "owl", "syllables": ["owl"], "ipa": "/aʊl/", "meaning": "n. 貓頭鷹" },
    { "level": 10, "word": "parcel", "syllables": ["par", "cel"], "ipa": "/ˈpɑːrsl/", "meaning": "v. 分為小部分" },
    { "level": 10, "word": "parking", "syllables": ["park", "ing"], "ipa": "/ˈpɑːrkɪŋ/", "meaning": "n. 停車" },
    { "level": 10, "word": "part", "syllables": ["part"], "ipa": "/pɑːrt/", "meaning": "n. 部分" },
    { "level": 10, "word": "passion", "syllables": ["pas", "sion"], "ipa": "/ˈpæʃn/", "meaning": "n. 激越、憤怒" },
    { "level": 10, "word": "pub", "syllables": ["pub"], "ipa": "/pʌb/", "meaning": "n. 酒館、客棧" },
    { "level": 10, "word": "reader", "syllables": ["read", "er"], "ipa": "/ˈriːdər/", "meaning": "n. 讀者" },
    { "level": 10, "word": "reasonable", "syllables": ["rea", "son", "a", "ble"], "ipa": "/ˈriːznəbl/", "meaning": "adj. 合理的、正當的" },
    { "level": 10, "word": "research", "syllables": ["re", "search"], "ipa": "/ˈriːsɜːrtʃ/", "meaning": "n.v. 研究、調查" },
    { "level": 10, "word": "reservation", "syllables": ["res", "er", "va", "tion"], "ipa": "/ˌrezərˈveɪʃn/", "meaning": "n. 保留" },
    { "level": 10, "word": "reserve", "syllables": ["re", "serve"], "ipa": "/rɪˈzɜːrv/", "meaning": "v. 儲備、保存" },
    { "level": 10, "word": "riddle", "syllables": ["rid", "dle"], "ipa": "/ˈrɪdl/", "meaning": "n. 謎、謎語" },
    { "level": 10, "word": "running", "syllables": ["run", "ning"], "ipa": "/ˈrʌnɪŋ/", "meaning": "n. 奔、賽跑" },
    { "level": 10, "word": "schedule", "syllables": ["sched", "ule"], "ipa": "/ˈskedʒuːl/", "meaning": "n. 表、清單" },
    { "level": 10, "word": "schoolboy", "syllables": ["school", "boy"], "ipa": "/ˈskuːlbɔɪ/", "meaning": "n. 男學生" },
    { "level": 10, "word": "schoolmate", "syllables": ["school", "mate"], "ipa": "/ˈskuːlmeɪt/", "meaning": "n. 同學" },
    { "level": 10, "word": "scientific", "syllables": ["sci", "en", "tif", "ic"], "ipa": "/ˌsaɪənˈtɪfɪk/", "meaning": "adj. 科學的" },
    { "level": 10, "word": "scissors", "syllables": ["scis", "sors"], "ipa": "/ˈsɪzərz/", "meaning": "n. 剪刀" },
    { "level": 10, "word": "seafood", "syllables": ["sea", "food"], "ipa": "/ˈsiːfuːd/", "meaning": "n. 海產食品" },
    { "level": 10, "word": "self", "syllables": ["self"], "ipa": "/self/", "meaning": "n. 自己" },
    { "level": 10, "word": "sentence", "syllables": ["sen", "tence"], "ipa": "/ˈsentəns/", "meaning": "n. 句子" },
    { "level": 10, "word": "sex", "syllables": ["sex"], "ipa": "/seks/", "meaning": "n. 性別" },
    { "level": 10, "word": "sexy", "syllables": ["sex", "y"], "ipa": "/ˈseksi/", "meaning": "adj. 性感的" },
    { "level": 10, "word": "shadow", "syllables": ["shad", "ow"], "ipa": "/ˈʃædoʊ/", "meaning": "n. 蔭；陰暗處" },
    { "level": 10, "word": "smoking", "syllables": ["smok", "ing"], "ipa": "/ˈsmoʊkɪŋ/", "meaning": "n. 抽煙、吸煙" },
    { "level": 10, "word": "smoky", "syllables": ["smok", "y"], "ipa": "/ˈsmoʊki/", "meaning": "adj. 冒煙的" },
    { "level": 10, "word": "smooth", "syllables": ["smooth"], "ipa": "/smuːð/", "meaning": "adj. 平滑的" },
    { "level": 10, "word": "sneeze", "syllables": ["sneeze"], "ipa": "/sniːz/", "meaning": "n. 噴嚏" },
    { "level": 10, "word": "snowman", "syllables": ["snow", "man"], "ipa": "/ˈsnoʊmæn/", "meaning": "n. 雪人" },
    { "level": 10, "word": "socket", "syllables": ["sock", "et"], "ipa": "/ˈsɑːkɪt/", "meaning": "n. 插座" },
    { "level": 10, "word": "softball", "syllables": ["soft", "ball"], "ipa": "/ˈsɔːftbɔːl/", "meaning": "n. 壘球" },
    { "level": 10, "word": "software", "syllables": ["soft", "ware"], "ipa": "/ˈsɔːftwer/", "meaning": "n. 軟體" },
    { "level": 10, "word": "soil", "syllables": ["soil"], "ipa": "/sɔɪl/", "meaning": "n. 土、泥土" },
    { "level": 10, "word": "solar", "syllables": ["so", "lar"], "ipa": "/ˈsoʊlər/", "meaning": "adj. 太陽的、日光的" },
    { "level": 10, "word": "somehow", "syllables": ["some", "how"], "ipa": "/ˈsʌmhaʊ/", "meaning": "adv. 由於某種原因" },
    { "level": 10, "word": "sometime", "syllables": ["some", "time"], "ipa": "/ˈsʌmtaɪm/", "meaning": "adv. 有些時候" },
    { "level": 10, "word": "somewhat", "syllables": ["some", "what"], "ipa": "/ˈsʌmwʌt/", "meaning": "adv. 有點、稍微" },
    { "level": 10, "word": "south-east", "syllables": ["south", "east"], "ipa": "/ˌsaʊθˈiːst/", "meaning": "n. 東南方" },
    { "level": 10, "word": "southwest", "syllables": ["south", "west"], "ipa": "/ˌsaʊθˈwest/", "meaning": "n. 西南方" },
    { "level": 10, "word": "spell", "syllables": ["spell"], "ipa": "/spel/", "meaning": "v. 用字母拼；拼寫" },
    { "level": 10, "word": "spicy", "syllables": ["spi", "cy"], "ipa": "/ˈspaɪsi/", "meaning": "adj. 加有香料的；香的" },
    { "level": 10, "word": "spinach", "syllables": ["spin", "ach"], "ipa": "/ˈspɪnɪtʃ/", "meaning": "n. 菠菜" },
    { "level": 10, "word": "stepfather", "syllables": ["step", "fa", "ther"], "ipa": "/ˈstepfɑːðər/", "meaning": "n. 繼父、後父" },
    { "level": 10, "word": "stepmother", "syllables": ["step", "moth", "er"], "ipa": "/ˈstepmʌðər/", "meaning": "n. 繼母、後母" },
    { "level": 10, "word": "storyteller", "syllables": ["sto", "ry", "tel", "ler"], "ipa": "/ˈstɔːritelər/", "meaning": "n. 講故事的人" },
    { "level": 10, "word": "stretch", "syllables": ["stretch"], "ipa": "/stretʃ/", "meaning": "v. 伸直、伸長" },
    { "level": 10, "word": "underground", "syllables": ["un", "der", "ground"], "ipa": "/ˌʌndərˈɡraʊnd/", "meaning": "adj. 地下的" },
    { "level": 10, "word": "upset", "syllables": ["up", "set"], "ipa": "/ˌʌpˈset/", "meaning": "n. 弄翻、打翻" },
    { "level": 10, "word": "well-known", "syllables": ["well", "known"], "ipa": "/ˌwel ˈnoʊn/", "meaning": "adj. 眾所周知的" }