// words.js - OPA 單字大資料庫 (依據圖片 L1-L8 完整校對版本)
const allWords = [
    // === Level 1 (基礎單字) ===
    { "level": 1, "word": "after", "syllables": ["af", "ter"], "ipa": "/ˈæftər/", "meaning": "prep.conj. 在...之後" },
    { "level": 1, "word": "afternoon", "syllables": ["af", "ter", "noon"], "ipa": "/ˌæftərˈnuːn/", "meaning": "n. 下午" },
    { "level": 1, "word": "ago", "syllables": ["a", "go"], "ipa": "/əˈɡoʊ/", "meaning": "adv. 在...以前" },
    { "level": 1, "word": "apple", "syllables": ["ap", "ple"], "ipa": "/ˈæpl/", "meaning": "n. 蘋果" },
    { "level": 1, "word": "April", "syllables": ["A", "pril"], "ipa": "/ˈeɪprəl/", "meaning": "n. 四月" },
    { "level": 1, "word": "arm", "syllables": ["arm"], "ipa": "/ɑːrm/", "meaning": "n. 手臂" },
    { "level": 1, "word": "August", "syllables": ["Au", "gust"], "ipa": "/ɔːˈɡʌst/", "meaning": "n. 八月" },
    { "level": 1, "word": "bad", "syllables": ["bad"], "ipa": "/bæd/", "meaning": "adj. 壞的" },
    { "level": 1, "word": "bag", "syllables": ["bag"], "ipa": "/bæɡ/", "meaning": "n. 袋子" },
    { "level": 1, "word": "ball", "syllables": ["ball"], "ipa": "/bɔːl/", "meaning": "n. 球" },
    { "level": 1, "word": "banana", "syllables": ["ba", "nan", "a"], "ipa": "/bəˈnænə/", "meaning": "n. 香蕉" },
    { "level": 1, "word": "bathroom", "syllables": ["bath", "room"], "ipa": "/ˈbæθruːm/", "meaning": "n. 浴室" },
    { "level": 1, "word": "bear", "syllables": ["bear"], "ipa": "/ber/", "meaning": "n. 熊" },
    { "level": 1, "word": "bed", "syllables": ["bed"], "ipa": "/bed/", "meaning": "n. 床" },
    { "level": 1, "word": "bedroom", "syllables": ["bed", "room"], "ipa": "/ˈbedruːm/", "meaning": "n. 臥室" },
    { "level": 1, "word": "bee", "syllables": ["bee"], "ipa": "/biː/", "meaning": "n. 蜜蜂" },
    { "level": 1, "word": "bell", "syllables": ["bell"], "ipa": "/bel/", "meaning": "n. 鐘、鈴" },
    { "level": 1, "word": "bicycle", "syllables": ["bi", "cy", "cle"], "ipa": "/ˈbaɪsɪkl/", "meaning": "n. 腳踏車" },
    { "level": 1, "word": "big", "syllables": ["big"], "ipa": "/bɪɡ/", "meaning": "adj. 大的" },
    { "level": 1, "word": "bird", "syllables": ["bird"], "ipa": "/bɜːrd/", "meaning": "n. 鳥" },
    { "level": 1, "word": "birthday", "syllables": ["birth", "day"], "ipa": "/ˈbɜːrθdeɪ/", "meaning": "n. 生日" },
    { "level": 1, "word": "black", "syllables": ["black"], "ipa": "/blæk/", "meaning": "adj. 黑色的" },
    { "level": 1, "word": "blackboard", "syllables": ["black", "board"], "ipa": "/ˈblækbɔːrd/", "meaning": "n. 黑板" },
    { "level": 1, "word": "blue", "syllables": ["blue"], "ipa": "/bluː/", "meaning": "adj. 藍色的" },
    { "level": 1, "word": "body", "syllables": ["bod", "y"], "ipa": "/ˈbɑːdi/", "meaning": "n. 身體" },
    { "level": 1, "word": "book", "syllables": ["book"], "ipa": "/bʊk/", "meaning": "n. 書本" },
    { "level": 1, "word": "box", "syllables": ["box"], "ipa": "/bɑːks/", "meaning": "n. 盒子" },
    { "level": 1, "word": "boy", "syllables": ["boy"], "ipa": "/bɔɪ/", "meaning": "n. 男孩" },
    { "level": 1, "word": "breakfast", "syllables": ["break", "fast"], "ipa": "/ˈbrekfəst/", "meaning": "n. 早餐" },
    { "level": 1, "word": "brother", "syllables": ["broth", "er"], "ipa": "/ˈbrʌðər/", "meaning": "n. 兄弟" },
    { "level": 1, "word": "brown", "syllables": ["brown"], "ipa": "/braʊn/", "meaning": "adj. 棕色的" },
    { "level": 1, "word": "bus", "syllables": ["bus"], "ipa": "/bʌs/", "meaning": "n. 公車" },
    { "level": 1, "word": "cake", "syllables": ["cake"], "ipa": "/keɪk/", "meaning": "n. 蛋糕" },
    { "level": 1, "word": "candy", "syllables": ["can", "dy"], "ipa": "/ˈkændi/", "meaning": "n. 糖果" },
    { "level": 1, "word": "cap", "syllables": ["cap"], "ipa": "/kæp/", "meaning": "n. 帽子" },
    { "level": 1, "word": "car", "syllables": ["car"], "ipa": "/kɑːr/", "meaning": "n. 車子" },
    { "level": 1, "word": "cat", "syllables": ["cat"], "ipa": "/kæt/", "meaning": "n. 貓" },
    { "level": 1, "word": "chair", "syllables": ["chair"], "ipa": "/tʃer/", "meaning": "n. 椅子" },
    { "level": 1, "word": "chalk", "syllables": ["chalk"], "ipa": "/tʃɔːk/", "meaning": "n. 粉筆" },
    { "level": 1, "word": "chicken", "syllables": ["chick", "en"], "ipa": "/ˈtʃɪkɪn/", "meaning": "n. 雞肉" },
    { "level": 1, "word": "chocolate", "syllables": ["choc", "o", "late"], "ipa": "/ˈtʃɑːklət/", "meaning": "n. 巧克力" },
    { "level": 1, "word": "class", "syllables": ["class"], "ipa": "/klæs/", "meaning": "n. 班級" },
    { "level": 1, "word": "clock", "syllables": ["clock"], "ipa": "/klɑːk/", "meaning": "n. 時鐘" },
    { "level": 1, "word": "coffee", "syllables": ["cof", "fee"], "ipa": "/ˈkɔːfi/", "meaning": "n. 咖啡" },
    { "level": 1, "word": "color", "syllables": ["col", "or"], "ipa": "/ˈkʌlər/", "meaning": "n. 顏色" },
    { "level": 1, "word": "computer", "syllables": ["com", "pu", "ter"], "ipa": "/kəmˈpjuːtər/", "meaning": "n. 電腦" },
    { "level": 1, "word": "cookie", "syllables": ["cook", "ie"], "ipa": "/ˈkʊki/", "meaning": "n. 餅乾" },
    { "level": 1, "word": "cup", "syllables": ["cup"], "ipa": "/kʌp/", "meaning": "n. 杯子" },
    { "level": 1, "word": "dad", "syllables": ["dad"], "ipa": "/dæd/", "meaning": "n. 爸爸" },
    { "level": 1, "word": "dance", "syllables": ["dance"], "ipa": "/dæns/", "meaning": "v. 跳舞" },
    { "level": 1, "word": "day", "syllables": ["day"], "ipa": "/deɪ/", "meaning": "n. 白天" },
    { "level": 1, "word": "December", "syllables": ["De", "cem", "ber"], "ipa": "/dɪˈsembər/", "meaning": "n. 十二月" },
    { "level": 1, "word": "desk", "syllables": ["desk"], "ipa": "/desk/", "meaning": "n. 書桌" },
    { "level": 1, "word": "dinner", "syllables": ["din", "ner"], "ipa": "/ˈdɪnər/", "meaning": "n. 晚餐" },
    { "level": 1, "word": "doctor", "syllables": ["doc", "tor"], "ipa": "/ˈdɑːktər/", "meaning": "n. 醫生" },
    { "level": 1, "word": "dog", "syllables": ["dog"], "ipa": "/dɔːɡ/", "meaning": "n. 狗" },
    { "level": 1, "word": "doll", "syllables": ["doll"], "ipa": "/dɑːl/", "meaning": "n. 娃娃" },
    { "level": 1, "word": "door", "syllables": ["door"], "ipa": "/dɔːr/", "meaning": "n. 門" },
    { "level": 1, "word": "dress", "syllables": ["dress"], "ipa": "/dres/", "meaning": "n. 洋裝" },
    { "level": 1, "word": "ear", "syllables": ["ear"], "ipa": "/ɪr/", "meaning": "n. 耳朵" },
    { "level": 1, "word": "eat", "syllables": ["eat"], "ipa": "/iːt/", "meaning": "v. 吃" },
    { "level": 1, "word": "egg", "syllables": ["egg"], "ipa": "/eɡ/", "meaning": "n. 蛋" },
    { "level": 1, "word": "elephant", "syllables": ["el", "e", "phant"], "ipa": "/ˈelɪfənt/", "meaning": "n. 大象" },
    { "level": 1, "word": "evening", "syllables": ["e", "ve", "ning"], "ipa": "/ˈiːvnɪŋ/", "meaning": "n. 晚上" },
    { "level": 1, "word": "eye", "syllables": ["eye"], "ipa": "/aɪ/", "meaning": "n. 眼睛" },
    { "level": 1, "word": "face", "syllables": ["face"], "ipa": "/feɪs/", "meaning": "n. 臉" },
    { "level": 1, "word": "father", "syllables": ["fa", "ther"], "ipa": "/ˈfɑːðər/", "meaning": "n. 父親" },
    { "level": 1, "word": "February", "syllables": ["Feb", "ru", "ar", "y"], "ipa": "/ˈfebrueri/", "meaning": "n. 二月" },
    { "level": 1, "word": "finger", "syllables": ["fin", "ger"], "ipa": "/ˈfɪŋɡər/", "meaning": "n. 手指" },
    { "level": 1, "word": "fish", "syllables": ["fish"], "ipa": "/fɪʃ/", "meaning": "n. 魚" },
    { "level": 1, "word": "flower", "syllables": ["flow", "er"], "ipa": "/ˈflaʊər/", "meaning": "n. 花朵" },
    { "level": 1, "word": "food", "syllables": ["food"], "ipa": "/fuːd/", "meaning": "n. 食物" },
    { "level": 1, "word": "foot", "syllables": ["foot"], "ipa": "/fʊt/", "meaning": "n. 腳" },
    { "level": 1, "word": "Friday", "syllables": ["Fri", "day"], "ipa": "/ˈfraɪdeɪ/", "meaning": "n. 星期五" },
    { "level": 1, "word": "friend", "syllables": ["friend"], "ipa": "/frend/", "meaning": "n. 朋友" },
    { "level": 1, "word": "girl", "syllables": ["girl"], "ipa": "/ɡɜːrl/", "meaning": "n. 女孩" },
    { "level": 1, "word": "goat", "syllables": ["goat"], "ipa": "/ɡoʊt/", "meaning": "n. 山羊" },
    { "level": 1, "word": "good", "syllables": ["good"], "ipa": "/ɡʊd/", "meaning": "adj. 好的" },
    { "level": 1, "word": "green", "syllables": ["green"], "ipa": "/ɡriːn/", "meaning": "adj. 綠色的" },
    { "level": 1, "word": "hair", "syllables": ["hair"], "ipa": "/her/", "meaning": "n. 頭髮" },
    { "level": 1, "word": "hamburger", "syllables": ["ham", "burg", "er"], "ipa": "/ˈhæmbɜːrɡər/", "meaning": "n. 漢堡" },
    { "level": 1, "word": "hand", "syllables": ["hand"], "ipa": "/hænd/", "meaning": "n. 手" },
    { "level": 1, "word": "happy", "syllables": ["hap", "py"], "ipa": "/ˈhæpi/", "meaning": "adj. 快樂的" },
    { "level": 1, "word": "hat", "syllables": ["hat"], "ipa": "/hæt/", "meaning": "n. 帽子" },
    { "level": 1, "word": "head", "syllables": ["head"], "ipa": "/hed/", "meaning": "n. 頭" },
    { "level": 1, "word": "hello", "syllables": ["hel", "lo"], "ipa": "/həˈloʊ/", "meaning": "int. 你好" },
    { "level": 1, "word": "hi", "syllables": ["hi"], "ipa": "/haɪ/", "meaning": "int. 嗨" },
    { "level": 1, "word": "homework", "syllables": ["home", "work"], "ipa": "/ˈhoʊmwɜːrk/", "meaning": "n. 作業" },
    { "level": 1, "word": "horse", "syllables": ["horse"], "ipa": "/hɔːrs/", "meaning": "n. 馬" },
    { "level": 1, "word": "hot", "syllables": ["hot"], "ipa": "/hɑːt/", "meaning": "adj. 熱的" },
    { "level": 1, "word": "house", "syllables": ["house"], "ipa": "/haʊs/", "meaning": "n. 房子" },
    { "level": 1, "word": "jacket", "syllables": ["jack", "et"], "ipa": "/ˈdʒækɪt/", "meaning": "n. 夾克" },
    { "level": 1, "word": "January", "syllables": ["Jan", "u", "ar", "y"], "ipa": "/ˈdʒænjueri/", "meaning": "n. 一月" },
    { "level": 1, "word": "juice", "syllables": ["juice"], "ipa": "/dʒuːs/", "meaning": "n. 果汁" },
    { "level": 1, "word": "July", "syllables": ["Ju", "ly"], "ipa": "/dʒuˈlaɪ/", "meaning": "n. 七月" },
    { "level": 1, "word": "jump", "syllables": ["jump"], "ipa": "/dʒʌmp/", "meaning": "v. 跳" },
    { "level": 1, "word": "June", "syllables": ["June"], "ipa": "/dʒuːn/", "meaning": "n. 六月" },
    { "level": 1, "word": "kitchen", "syllables": ["kit", "chen"], "ipa": "/ˈkɪtʃɪn/", "meaning": "n. 廚房" },
    { "level": 1, "word": "knee", "syllables": ["knee"], "ipa": "/niː/", "meaning": "n. 膝蓋" },
    { "level": 1, "word": "know", "syllables": ["know"], "ipa": "/noʊ/", "meaning": "v. 知道" },
    { "level": 1, "word": "leg", "syllables": ["leg"], "ipa": "/leɡ/", "meaning": "n. 腿" },
    { "level": 1, "word": "lemon", "syllables": ["lem", "on"], "ipa": "/ˈlemən/", "meaning": "n. 檸檬" },
    { "level": 1, "word": "lion", "syllables": ["li", "on"], "ipa": "/ˈlaɪən/", "meaning": "n. 獅子" },
    { "level": 1, "word": "long", "syllables": ["long"], "ipa": "/lɔːŋ/", "meaning": "adj. 長的" },
    { "level": 1, "word": "love", "syllables": ["love"], "ipa": "/lʌv/", "meaning": "v. 愛" },
    { "level": 1, "word": "lunch", "syllables": ["lunch"], "ipa": "/lʌntʃ/", "meaning": "n. 午餐" },
    { "level": 1, "word": "March", "syllables": ["March"], "ipa": "/mɑːrtʃ/", "meaning": "n. 三月" },
    { "level": 1, "word": "May", "syllables": ["May"], "ipa": "/meɪ/", "meaning": "n. 五月" },
    { "level": 1, "word": "milk", "syllables": ["milk"], "ipa": "/mɪlk/", "meaning": "n. 牛奶" },
    { "level": 1, "word": "Monday", "syllables": ["Mon", "day"], "ipa": "/ˈmʌndeɪ/", "meaning": "n. 星期一" },
    { "level": 1, "word": "monkey", "syllables": ["mon", "key"], "ipa": "/ˈmʌŋki/", "meaning": "n. 猴子" },
    { "level": 1, "word": "morning", "syllables": ["morn", "ing"], "ipa": "/ˈmɔːrnɪŋ/", "meaning": "n. 早上" },
    { "level": 1, "word": "mother", "syllables": ["moth", "er"], "ipa": "/ˈmʌðər/", "meaning": "n. 母親" },
    { "level": 1, "word": "mouse", "syllables": ["mouse"], "ipa": "/maʊs/", "meaning": "n. 老鼠" },
    { "level": 1, "word": "mouth", "syllables": ["mouth"], "ipa": "/maʊθ/", "meaning": "n. 嘴巴" },
    { "level": 1, "word": "name", "syllables": ["name"], "ipa": "/neɪm/", "meaning": "n. 名字" },
    { "level": 1, "word": "new", "syllables": ["new"], "ipa": "/nuː/", "meaning": "adj. 新的" },
    { "level": 1, "word": "nice", "syllables": ["nice"], "ipa": "/naɪs/", "meaning": "adj. 好的" },
    { "level": 1, "word": "nose", "syllables": ["nose"], "ipa": "/noʊz/", "meaning": "n. 鼻子" },
    { "level": 1, "word": "notebook", "syllables": ["note", "book"], "ipa": "/ˈnoʊtbʊk/", "meaning": "n. 筆記本" },
    { "level": 1, "word": "November", "syllables": ["No", "vem", "ber"], "ipa": "/noʊˈvembər/", "meaning": "n. 十一月" },
    { "level": 1, "word": "October", "syllables": ["Oc", "to", "ber"], "ipa": "/ɑːkˈtoʊbər/", "meaning": "n. 十月" },
    { "level": 1, "word": "orange", "syllables": ["o", "range"], "ipa": "/ˈɔːrɪndʒ/", "meaning": "n. 柳橙" },
    { "level": 1, "word": "paper", "syllables": ["pa", "per"], "ipa": "/ˈpeɪpər/", "meaning": "n. 紙" },
    { "level": 1, "word": "pen", "syllables": ["pen"], "ipa": "/pen/", "meaning": "n. 筆" },
    { "level": 1, "word": "pencil", "syllables": ["pen", "cil"], "ipa": "/ˈpensl/", "meaning": "n. 鉛筆" },
    { "level": 1, "word": "pie", "syllables": ["pie"], "ipa": "/paɪ/", "meaning": "n. 派" },
    { "level": 1, "word": "pig", "syllables": ["pig"], "ipa": "/pɪɡ/", "meaning": "n. 豬" },
    { "level": 1, "word": "pink", "syllables": ["pink"], "ipa": "/pɪŋk/", "meaning": "adj. 粉紅色的" },
    { "level": 1, "word": "pizza", "syllables": ["piz", "za"], "ipa": "/ˈpiːtsə/", "meaning": "n. 披薩" },
    { "level": 1, "word": "plane", "syllables": ["plane"], "ipa": "/pleɪn/", "meaning": "n. 飛機" },
    { "level": 1, "word": "rabbit", "syllables": ["rab", "bit"], "ipa": "/ˈræbɪt/", "meaning": "n. 兔子" },
    { "level": 1, "word": "rain", "syllables": ["rain"], "ipa": "/reɪn/", "meaning": "n.v. 雨" },
    { "level": 1, "word": "rainy", "syllables": ["rain", "y"], "ipa": "/ˈreɪni/", "meaning": "adj. 下雨的" },
    { "level": 1, "word": "red", "syllables": ["red"], "ipa": "/red/", "meaning": "adj. 紅色的" },
    { "level": 1, "word": "rice", "syllables": ["rice"], "ipa": "/raɪs/", "meaning": "n. 米飯" },
    { "level": 1, "word": "room", "syllables": ["room"], "ipa": "/ruːm/", "meaning": "n. 房間" },
    { "level": 1, "word": "sandwich", "syllables": ["sand", "wich"], "ipa": "/ˈsænwɪtʃ/", "meaning": "n. 三明治" },
    { "level": 1, "word": "Saturday", "syllables": ["Sat", "ur", "day"], "ipa": "/ˈsætərdeɪ/", "meaning": "n. 星期六" },
    { "level": 1, "word": "school", "syllables": ["school"], "ipa": "/skuːl/", "meaning": "n. 學校" },
    { "level": 1, "word": "September", "syllables": ["Sep", "tem", "ber"], "ipa": "/sepˈtembər/", "meaning": "n. 九月" },
    { "level": 1, "word": "sheep", "syllables": ["sheep"], "ipa": "/ʃiːp/", "meaning": "n. 綿羊" },
    { "level": 1, "word": "shirt", "syllables": ["shirt"], "ipa": "/ʃɜːrt/", "meaning": "n. 襯衫" },
    { "level": 1, "word": "shoe", "syllables": ["shoe"], "ipa": "/ʃuː/", "meaning": "n. 鞋子" },
    { "level": 1, "word": "short", "syllables": ["short"], "ipa": "/ʃɔːrt/", "meaning": "adj. 短的" },
    { "level": 1, "word": "sing", "syllables": ["sing"], "ipa": "/sɪŋ/", "meaning": "v. 唱歌" },
    { "level": 1, "word": "sister", "syllables": ["sis", "ter"], "ipa": "/ˈsɪstər/", "meaning": "n. 姊妹" },
    { "level": 1, "word": "skirt", "syllables": ["skirt"], "ipa": "/skɜːrt/", "meaning": "n. 裙子" },
    { "level": 1, "word": "small", "syllables": ["small"], "ipa": "/smɔːl/", "meaning": "adj. 小的" },
    { "level": 1, "word": "snake", "syllables": ["snake"], "ipa": "/sneɪk/", "meaning": "n. 蛇" },
    { "level": 1, "word": "sofa", "syllables": ["so", "fa"], "ipa": "/ˈsoʊfə/", "meaning": "n. 沙發" },
    { "level": 1, "word": "sorry", "syllables": ["sor", "ry"], "ipa": "/ˈsɔːri/", "meaning": "adj. 抱歉的" },
    { "level": 1, "word": "stand", "syllables": ["stand"], "ipa": "/stænd/", "meaning": "v. 站立" },
    { "level": 1, "word": "store", "syllables": ["store"], "ipa": "/stɔːr/", "meaning": "n. 商店" },
    { "level": 1, "word": "student", "syllables": ["stu", "dent"], "ipa": "/ˈstuːdnt/", "meaning": "n. 學生" },
    { "level": 1, "word": "sun", "syllables": ["sun"], "ipa": "/sʌn/", "meaning": "n. 太陽" },
    { "level": 1, "word": "Sunday", "syllables": ["Sun", "day"], "ipa": "/ˈsʌndeɪ/", "meaning": "n. 星期日" },
    { "level": 1, "word": "sunny", "syllables": ["sun", "ny"], "ipa": "/ˈsʌni/", "meaning": "adj. 晴朗的" },
    { "level": 1, "word": "table", "syllables": ["ta", "ble"], "ipa": "/ˈteɪbl/", "meaning": "n. 桌子" },
    { "level": 1, "word": "tall", "syllables": ["tall"], "ipa": "/tɔːl/", "meaning": "adj. 高的" },
    { "level": 1, "word": "tea", "syllables": ["tea"], "ipa": "/tiː/", "meaning": "n. 茶" },
    { "level": 1, "word": "teacher", "syllables": ["teach", "er"], "ipa": "/ˈtiːtʃər/", "meaning": "n. 老師" },
    { "level": 1, "word": "television", "syllables": ["tel", "e", "vi", "sion"], "ipa": "/ˈtelɪvɪʒn/", "meaning": "n. 電視" },
    { "level": 1, "word": "ten", "syllables": ["ten"], "ipa": "/ten/", "meaning": "num. 十" },
    { "level": 1, "word": "thank", "syllables": ["thank"], "ipa": "/θæŋk/", "meaning": "v. 謝謝" },
    { "level": 1, "word": "tiger", "syllables": ["ti", "ger"], "ipa": "/ˈtaɪɡər/", "meaning": "n. 老虎" },
    { "level": 1, "word": "time", "syllables": ["time"], "ipa": "/taɪm/", "meaning": "n. 時間" },
    { "level": 1, "word": "tomato", "syllables": ["to", "ma", "to"], "ipa": "/təˈmeɪtoʊ/", "meaning": "n. 番茄" },
    { "level": 1, "word": "tooth", "syllables": ["tooth"], "ipa": "/tuːθ/", "meaning": "n. 牙齒" },
    { "level": 1, "word": "tree", "syllables": ["tree"], "ipa": "/triː/", "meaning": "n. 樹" },
    { "level": 1, "word": "Tuesday", "syllables": ["Tues", "day"], "ipa": "/ˈtuːzdeɪ/", "meaning": "n. 星期二" },
    { "level": 1, "word": "twelve", "syllables": ["twelve"], "ipa": "/twelv/", "meaning": "num. 十二" },
    { "level": 1, "word": "twenty", "syllables": ["twen", "ty"], "ipa": "/ˈtwenti/", "meaning": "num. 二十" },
    { "level": 1, "word": "umbrella", "syllables": ["um", "brel", "la"], "ipa": "/ʌmˈbrelə/", "meaning": "n. 雨傘" },
    { "level": 1, "word": "uncle", "syllables": ["un", "cle"], "ipa": "/ˈʌŋkl/", "meaning": "n. 叔叔、伯伯" },
    { "level": 1, "word": "under", "syllables": ["un", "der"], "ipa": "/ˈʌndər/", "meaning": "prep. 在...下面" },
    { "level": 1, "word": "want", "syllables": ["want"], "ipa": "/wɑːnt/", "meaning": "v. 想要" },
    { "level": 1, "word": "watch", "syllables": ["watch"], "ipa": "/wɑːtʃ/", "meaning": "v.n. 看；手錶" },
    { "level": 1, "word": "water", "syllables": ["wa", "ter"], "ipa": "/ˈwɔːtər/", "meaning": "n. 水" },
    { "level": 1, "word": "Wednesday", "syllables": ["Wednes", "day"], "ipa": "/ˈwenzdeɪ/", "meaning": "n. 星期三" },
    { "level": 1, "word": "week", "syllables": ["week"], "ipa": "/wiːk/", "meaning": "n. 星期" },
    { "level": 1, "word": "white", "syllables": ["white"], "ipa": "/waɪt/", "meaning": "adj. 白色的" },
    { "level": 1, "word": "window", "syllables": ["win", "dow"], "ipa": "/ˈwɪndoʊ/", "meaning": "n. 窗戶" },
    { "level": 1, "word": "year", "syllables": ["year"], "ipa": "/jɪr/", "meaning": "n. 年" },
    { "level": 1, "word": "yellow", "syllables": ["yel", "low"], "ipa": "/ˈjeloʊ/", "meaning": "adj. 黃色的" },
    { "level": 1, "word": "zoo", "syllables": ["zoo"], "ipa": "/zuː/", "meaning": "n. 動物園" },

    // === Level 2 (進階單字) ===
    { "level": 2, "word": "A.M.", "syllables": ["A.M."], "ipa": "/ˌeɪ ˈem/", "meaning": "abbr. 上午" },
    { "level": 2, "word": "about", "syllables": ["a", "bout"], "ipa": "/əˈbaʊt/", "meaning": "prep. 關於" },
    { "level": 2, "word": "again", "syllables": ["a", "gain"], "ipa": "/əˈɡen/", "meaning": "adv. 再次" },
    { "level": 2, "word": "age", "syllables": ["age"], "ipa": "/eɪdʒ/", "meaning": "n. 年齡" },
    { "level": 2, "word": "airplane", "syllables": ["air", "plane"], "ipa": "/ˈerpleɪn/", "meaning": "n. 飛機" },
    { "level": 2, "word": "airport", "syllables": ["air", "port"], "ipa": "/ˈerpɔːrt/", "meaning": "n. 機場" },
    { "level": 2, "word": "all", "syllables": ["all"], "ipa": "/ɔːl/", "meaning": "adj. 全部的" },
    { "level": 2, "word": "animal", "syllables": ["an", "i", "mal"], "ipa": "/ˈænɪml/", "meaning": "n. 動物" },
    { "level": 2, "word": "answer", "syllables": ["an", "swer"], "ipa": "/ˈænsər/", "meaning": "v.n. 回答；答案" },
    { "level": 2, "word": "anybody", "syllables": ["an", "y", "bod", "y"], "ipa": "/ˈenibɑːdi/", "meaning": "pron. 任何人" },
    { "level": 2, "word": "autumn", "syllables": ["au", "tumn"], "ipa": "/ˈɔːtəm/", "meaning": "n. 秋天" },
    { "level": 2, "word": "bakery", "syllables": ["bak", "er", "y"], "ipa": "/ˈbeɪkəri/", "meaning": "n. 麵包店" },
    { "level": 2, "word": "baseball", "syllables": ["base", "ball"], "ipa": "/ˈbeɪsbɔːl/", "meaning": "n. 棒球" },
    { "level": 2, "word": "beautiful", "syllables": ["beau", "ti", "ful"], "ipa": "/ˈbjuːtɪfl/", "meaning": "adj. 美麗的" },
    { "level": 2, "word": "between", "syllables": ["be", "tween"], "ipa": "/bɪˈtwiːn/", "meaning": "prep. 在...之間" },
    { "level": 2, "word": "cheese", "syllables": ["cheese"], "ipa": "/tʃiːz/", "meaning": "n. 乳酪" },
    { "level": 2, "word": "circle", "syllables": ["cir", "cle"], "ipa": "/ˈsɜːrkl/", "meaning": "n. 圓圈" },
    { "level": 2, "word": "daughter", "syllables": ["daugh", "ter"], "ipa": "/ˈdɔːtər/", "meaning": "n. 女兒" },
    { "level": 2, "word": "everyone", "syllables": ["ev", "er", "y", "one"], "ipa": "/ˈevriwʌn/", "meaning": "pron. 每個人" },
    { "level": 2, "word": "exercise", "syllables": ["ex", "er", "cise"], "ipa": "/ˈeksərsaɪz/", "meaning": "v.n. 運動" },
    { "level": 2, "word": "favorite", "syllables": ["fa", "vor", "ite"], "ipa": "/ˈfeɪvərɪt/", "meaning": "adj. 最喜愛的" },
    { "level": 2, "word": "grandfather", "syllables": ["grand", "fa", "ther"], "ipa": "/ˈɡrænfɑːðər/", "meaning": "n. 爺爺、外公" },
    { "level": 2, "word": "hospital", "syllables": ["hos", "pi", "tal"], "ipa": "/ˈhɑːspɪtl/", "meaning": "n. 醫院" },
    { "level": 2, "word": "hundred", "syllables": ["hun", "dred"], "ipa": "/ˈhʌndrəd/", "meaning": "num. 一百" },
    { "level": 2, "word": "listen", "syllables": ["lis", "ten"], "ipa": "/ˈlɪsn/", "meaning": "v. 聽" },
    { "level": 2, "word": "marker", "syllables": ["mark", "er"], "ipa": "/ˈmɑːrkər/", "meaning": "n. 麥克筆" },
    { "level": 2, "word": "museum", "syllables": ["mu", "se", "um"], "ipa": "/mjuˈziːəm/", "meaning": "n. 博物館" },
    { "level": 2, "word": "often", "syllables": ["of", "ten"], "ipa": "/ˈɔːfn/", "meaning": "adv. 經常" },
    { "level": 2, "word": "playground", "syllables": ["play", "ground"], "ipa": "/ˈpleɪɡraʊnd/", "meaning": "n. 遊樂場" },
    { "level": 2, "word": "question", "syllables": ["ques", "tion"], "ipa": "/ˈkwestʃən/", "meaning": "n. 問題" },
    { "level": 2, "word": "quiet", "syllables": ["qui", "et"], "ipa": "/ˈkwaɪət/", "meaning": "adj. 安靜的" },
    { "level": 2, "word": "remember", "syllables": ["re", "mem", "ber"], "ipa": "/rɪˈmembər/", "meaning": "v. 記得" },
    { "level": 2, "word": "restaurant", "syllables": ["res", "tau", "rant"], "ipa": "/ˈrestrɑːnt/", "meaning": "n. 餐廳" },
    { "level": 2, "word": "sentence", "syllables": ["sen", "tence"], "ipa": "/ˈsentəns/", "meaning": "n. 句子" },
    { "level": 2, "word": "sometimes", "syllables": ["some", "times"], "ipa": "/ˈsʌmtaɪmz/", "meaning": "adv. 有時候" },
    { "level": 2, "word": "together", "syllables": ["to", "geth", "er"], "ipa": "/təˈɡeðər/", "meaning": "adv. 一起" },
    { "level": 2, "word": "vegetable", "syllables": ["veg", "e", "ta", "ble"], "ipa": "/ˈvedʒtəbl/", "meaning": "n. 蔬菜" },
    { "level": 2, "word": "yesterday", "syllables": ["yes", "ter", "day"], "ipa": "/ˈjestərdeɪ/", "meaning": "adv.n. 昨天" },

    // === Level 3 ===
    { "level": 3, "word": "afraid", "syllables": ["a", "fraid"], "ipa": "/əˈfreɪd/", "meaning": "adj. 害怕的" },
    { "level": 3, "word": "air", "syllables": ["air"], "ipa": "/er/", "meaning": "n. 空氣" },
    { "level": 3, "word": "almost", "syllables": ["al", "most"], "ipa": "/ˈɔːlmoʊst/", "meaning": "adv. 幾乎" },
    { "level": 3, "word": "America", "syllables": ["A", "mer", "i", "ca"], "ipa": "/əˈmerɪkə/", "meaning": "n. 美國" },
    { "level": 3, "word": "American", "syllables": ["A", "mer", "i", "can"], "ipa": "/əˈmerɪkən/", "meaning": "adj.n. 美國的；美國人" },
    { "level": 3, "word": "angry", "syllables": ["an", "gry"], "ipa": "/ˈæŋɡri/", "meaning": "adj. 生氣的" },
    { "level": 3, "word": "another", "syllables": ["a", "noth", "er"], "ipa": "/əˈnʌðər/", "meaning": "adj.pron. 另一個" },
    { "level": 3, "word": "anyone", "syllables": ["an", "y", "one"], "ipa": "/ˈeniwʌn/", "meaning": "pron. 任何人" },
    { "level": 3, "word": "anything", "syllables": ["an", "y", "thing"], "ipa": "/ˈeniθɪŋ/", "meaning": "pron. 任何事物" },
    { "level": 3, "word": "around", "syllables": ["a", "round"], "ipa": "/əˈraʊnd/", "meaning": "prep.adv. 在...四周" },
    { "level": 3, "word": "art", "syllables": ["art"], "ipa": "/ɑːrt/", "meaning": "n. 藝術" },
    { "level": 3, "word": "as", "syllables": ["as"], "ipa": "/æz/", "meaning": "adv.conj. 如同；當...時" },
    { "level": 3, "word": "beef", "syllables": ["beef"], "ipa": "/biːf/", "meaning": "n. 牛肉" },
    { "level": 3, "word": "belt", "syllables": ["belt"], "ipa": "/belt/", "meaning": "n. 腰帶" },
    { "level": 3, "word": "blind", "syllables": ["blind"], "ipa": "/blaɪnd/", "meaning": "adj. 瞎的" },
    { "level": 3, "word": "both", "syllables": ["both"], "ipa": "/boʊθ/", "meaning": "pron. 兩者都" },
    { "level": 3, "word": "bottle", "syllables": ["bot", "tle"], "ipa": "/ˈbɑːtl/", "meaning": "n. 瓶子" },
    { "level": 3, "word": "bowl", "syllables": ["bowl"], "ipa": "/boʊl/", "meaning": "n. 碗" },
    { "level": 3, "word": "busy", "syllables": ["bus", "y"], "ipa": "/ˈbɪzi/", "meaning": "adj. 忙碌的" },
    { "level": 3, "word": "but", "syllables": ["but"], "ipa": "/bʌt/", "meaning": "conj. 但是" },
    { "level": 3, "word": "catch", "syllables": ["catch"], "ipa": "/kætʃ/", "meaning": "v. 接住；抓" },
    { "level": 3, "word": "cheap", "syllables": ["cheap"], "ipa": "/tʃiːp/", "meaning": "adj. 便宜的" },
    { "level": 3, "word": "check", "syllables": ["check"], "ipa": "/tʃek/", "meaning": "v. 檢查" },
    { "level": 3, "word": "China", "syllables": ["Chi", "na"], "ipa": "/ˈtʃaɪnə/", "meaning": "n. 中國" },
    { "level": 3, "word": "Chinese", "syllables": ["Chi", "nese"], "ipa": "/ˌtʃaɪˈniːz/", "meaning": "adj.n. 中國的；中文" },
    { "level": 3, "word": "chopstick", "syllables": ["chop", "stick"], "ipa": "/ˈtʃɑːpstɪk/", "meaning": "n. 筷子" },
    { "level": 3, "word": "Christmas", "syllables": ["Christ", "mas"], "ipa": "/ˈkrɪsməs/", "meaning": "n. 聖誕節" },
    { "level": 3, "word": "city", "syllables": ["cit", "y"], "ipa": "/ˈsɪti/", "meaning": "n. 城市" },
    { "level": 3, "word": "classmate", "syllables": ["class", "mate"], "ipa": "/ˈklæsmeɪt/", "meaning": "n. 同學" },
    { "level": 3, "word": "clear", "syllables": ["clear"], "ipa": "/klɪr/", "meaning": "adj. 清楚的" },
    { "level": 3, "word": "close", "syllables": ["close"], "ipa": "/kloʊz/", "meaning": "v. 關閉" },
    { "level": 3, "word": "closet", "syllables": ["clos", "et"], "ipa": "/ˈklɑːzɪt/", "meaning": "n. 衣櫥" },
    { "level": 3, "word": "clothes", "syllables": ["clothes"], "ipa": "/kloʊðz/", "meaning": "n. 衣服" },
    { "level": 3, "word": "club", "syllables": ["club"], "ipa": "/klʌb/", "meaning": "n. 社團" },
    { "level": 3, "word": "dark", "syllables": ["dark"], "ipa": "/dɑːrk/", "meaning": "adj. 黑暗的" },
    { "level": 3, "word": "delicious", "syllables": ["de", "li", "cious"], "ipa": "/dɪˈlɪʃəs/", "meaning": "adj. 美味的" },
    { "level": 3, "word": "different", "syllables": ["dif", "fer", "ent"], "ipa": "/ˈdɪfrənt/", "meaning": "adj. 不同的" },
    { "level": 3, "word": "dish", "syllables": ["dish"], "ipa": "/dɪʃ/", "meaning": "n. 碟子；一道菜" },
    { "level": 3, "word": "dollar", "syllables": ["dol", "lar"], "ipa": "/ˈdɑːlər/", "meaning": "n. 元" },
    { "level": 3, "word": "down", "syllables": ["down"], "ipa": "/daʊn/", "meaning": "adv. 向下" },
    { "level": 3, "word": "dream", "syllables": ["dream"], "ipa": "/driːm/", "meaning": "n.v. 夢；做夢" },
    { "level": 3, "word": "drive", "syllables": ["drive"], "ipa": "/draɪv/", "meaning": "v. 開車" },
    { "level": 3, "word": "each", "syllables": ["each"], "ipa": "/iːtʃ/", "meaning": "adj.pron. 每個" },
    { "level": 3, "word": "early", "syllables": ["ear", "ly"], "ipa": "/ˈɜːrli/", "meaning": "adj.adv. 早的" },
    { "level": 3, "word": "easy", "syllables": ["ea", "sy"], "ipa": "/ˈiːzi/", "meaning": "adj. 容易的" },
    { "level": 3, "word": "else", "syllables": ["else"], "ipa": "/els/", "meaning": "adv. 其他" },
    { "level": 3, "word": "e-mail", "syllables": ["e-mail"], "ipa": "/ˈiːmeɪl/", "meaning": "n. 電子郵件" },
    { "level": 3, "word": "enough", "syllables": ["e", "nough"], "ipa": "/ɪˈnʌf/", "meaning": "adj.adv. 足夠的" },
    { "level": 3, "word": "ever", "syllables": ["ev", "er"], "ipa": "/ˈevər/", "meaning": "adv. 曾經" },
    { "level": 3, "word": "every", "syllables": ["ev", "er", "y"], "ipa": "/ˈevri/", "meaning": "adj. 每個" },
    { "level": 3, "word": "excellent", "syllables": ["ex", "cel", "lent"], "ipa": "/ˈeksələnt/", "meaning": "adj. 優秀的" },
    { "level": 3, "word": "farmer", "syllables": ["farm", "er"], "ipa": "/ˈfɑːrmər/", "meaning": "n. 農夫" },
    { "level": 3, "word": "fast", "syllables": ["fast"], "ipa": "/fæst/", "meaning": "adj.adv. 快的" },
    { "level": 3, "word": "feel", "syllables": ["feel"], "ipa": "/fiːl/", "meaning": "v. 感覺" },
    { "level": 3, "word": "few", "syllables": ["few"], "ipa": "/fjuː/", "meaning": "adj. 很少的" },
    { "level": 3, "word": "find", "syllables": ["find"], "ipa": "/faɪnd/", "meaning": "v. 找到" },
    { "level": 3, "word": "first", "syllables": ["first"], "ipa": "/fɜːrst/", "meaning": "adj.adv. 第一" },
    { "level": 3, "word": "fisherman", "syllables": ["fish", "er", "man"], "ipa": "/ˈfɪʃərmən/", "meaning": "n. 漁夫" },
    { "level": 3, "word": "fly", "syllables": ["fly"], "ipa": "/flaɪ/", "meaning": "n. 蒼蠅" },
    { "level": 3, "word": "fork", "syllables": ["fork"], "ipa": "/fɔːrk/", "meaning": "n. 叉子" },
    { "level": 3, "word": "free", "syllables": ["free"], "ipa": "/friː/", "meaning": "adj. 自由的；免費的" },
    { "level": 3, "word": "full", "syllables": ["full"], "ipa": "/fʊl/", "meaning": "adj. 滿的" },
    { "level": 3, "word": "garden", "syllables": ["gar", "den"], "ipa": "/ˈɡɑːrdn/", "meaning": "n. 花園" },
    { "level": 3, "word": "glass", "syllables": ["glass"], "ipa": "/ɡlæs/", "meaning": "n. 玻璃杯" },
    { "level": 3, "word": "glove", "syllables": ["glove"], "ipa": "/ɡlʌv/", "meaning": "n. 手套" },
    { "level": 3, "word": "grade", "syllables": ["grade"], "ipa": "/ɡreɪd/", "meaning": "n. 年級；成績" },
    { "level": 3, "word": "great", "syllables": ["great"], "ipa": "/ɡreɪt/", "meaning": "adj. 很棒的" },
    { "level": 3, "word": "half", "syllables": ["half"], "ipa": "/hæf/", "meaning": "adj.n. 一半" },
    { "level": 3, "word": "handsome", "syllables": ["hand", "some"], "ipa": "/ˈhænsəm/", "meaning": "adj. 英俊的" },
    { "level": 3, "word": "hard", "syllables": ["hard"], "ipa": "/hɑːrd/", "meaning": "adj.adv. 硬的；辛苦的" },
    { "level": 3, "word": "hear", "syllables": ["hear"], "ipa": "/hɪr/", "meaning": "v. 聽到" },
    { "level": 3, "word": "heart", "syllables": ["heart"], "ipa": "/hɑːrt/", "meaning": "n. 心臟" },
    { "level": 3, "word": "heavy", "syllables": ["heav", "y"], "ipa": "/ˈhevi/", "meaning": "adj. 重的" },
    { "level": 3, "word": "help", "syllables": ["help"], "ipa": "/help/", "meaning": "v. 幫助" },
    { "level": 3, "word": "hers", "syllables": ["hers"], "ipa": "/hɜːrz/", "meaning": "pron. 她的" },
    { "level": 3, "word": "herself", "syllables": ["her", "self"], "ipa": "/hərˈself/", "meaning": "pron. 她自己" },
    { "level": 3, "word": "high", "syllables": ["high"], "ipa": "/haɪ/", "meaning": "adj. 高的" },
    { "level": 3, "word": "himself", "syllables": ["him", "self"], "ipa": "/hɪmˈself/", "meaning": "pron. 他自己" },
    { "level": 3, "word": "holiday", "syllables": ["hol", "i", "day"], "ipa": "/ˈhɑːlədeɪ/", "meaning": "n. 假期" },
    { "level": 3, "word": "hope", "syllables": ["hope"], "ipa": "/hoʊp/", "meaning": "v.n. 希望" },
    { "level": 3, "word": "hour", "syllables": ["hour"], "ipa": "/ˈaʊər/", "meaning": "n. 小時" },
    { "level": 3, "word": "idea", "syllables": ["i", "de", "a"], "ipa": "/aɪˈdiːə/", "meaning": "n. 點子" },
    { "level": 3, "word": "important", "syllables": ["im", "por", "tant"], "ipa": "/ɪmˈpɔːrtnt/", "meaning": "adj. 重要的" },
    { "level": 3, "word": "inside", "syllables": ["in", "side"], "ipa": "/ˌɪnˈsaɪd/", "meaning": "prep. 在...裡面" },
    { "level": 3, "word": "Internet", "syllables": ["In", "ter", "net"], "ipa": "/ˈɪntərnet/", "meaning": "n. 網際網路" },
    { "level": 3, "word": "itself", "syllables": ["it", "self"], "ipa": "/ɪtˈself/", "meaning": "pron. 它自己" },
    { "level": 3, "word": "just", "syllables": ["just"], "ipa": "/dʒʌst/", "meaning": "adv. 剛好；只是" },
    { "level": 3, "word": "key", "syllables": ["key"], "ipa": "/kiː/", "meaning": "n. 鑰匙" },
    { "level": 3, "word": "kind", "syllables": ["kind"], "ipa": "/kaɪnd/", "meaning": "n. 種類" },
    { "level": 3, "word": "knife", "syllables": ["knife"], "ipa": "/naɪf/", "meaning": "n. 刀子" },
    { "level": 3, "word": "later", "syllables": ["lat", "er"], "ipa": "/ˈleɪtər/", "meaning": "adv. 稍後" },
    { "level": 3, "word": "lazy", "syllables": ["la", "zy"], "ipa": "/ˈleɪzi/", "meaning": "adj. 懶惰的" },
    { "level": 3, "word": "learn", "syllables": ["learn"], "ipa": "/lɜːrn/", "meaning": "v. 學習" },
    { "level": 3, "word": "library", "syllables": ["li", "brar", "y"], "ipa": "/ˈlaɪbreri/", "meaning": "n. 圖書館" },
    { "level": 3, "word": "life", "syllables": ["life"], "ipa": "/laɪf/", "meaning": "n. 生命" },
    { "level": 3, "word": "light", "syllables": ["light"], "ipa": "/laɪt/", "meaning": "n.adj. 燈；輕的" },
    { "level": 3, "word": "little", "syllables": ["lit", "tle"], "ipa": "/ˈlɪtl/", "meaning": "adj. 一點點" },
    { "level": 3, "word": "low", "syllables": ["low"], "ipa": "/loʊ/", "meaning": "adj. 低的" },
    { "level": 3, "word": "lucky", "syllables": ["luck", "y"], "ipa": "/ˈlʌki/", "meaning": "adj. 幸運的" },
    { "level": 3, "word": "mail", "syllables": ["mail"], "ipa": "/meɪl/", "meaning": "n.v. 信件；郵寄" },
    { "level": 3, "word": "mailman", "syllables": ["mail", "man"], "ipa": "/ˈmeɪlmæn/", "meaning": "n. 郵差" },
    { "level": 3, "word": "meat", "syllables": ["meat"], "ipa": "/miːt/", "meaning": "n. 肉" },
    { "level": 3, "word": "meeting", "syllables": ["meet", "ing"], "ipa": "/ˈmiːtɪŋ/", "meaning": "n. 會議" },
    { "level": 3, "word": "menu", "syllables": ["men", "u"], "ipa": "/ˈmenjuː/", "meaning": "n. 菜單" },
    { "level": 3, "word": "million", "syllables": ["mil", "lion"], "ipa": "/ˈmɪljən/", "meaning": "num. 百萬" },
    { "level": 3, "word": "mine", "syllables": ["mine"], "ipa": "/maɪn/", "meaning": "pron. 我的" },
    { "level": 3, "word": "minute", "syllables": ["min", "ute"], "ipa": "/ˈmɪnɪt/", "meaning": "n. 分鐘" },
    { "level": 3, "word": "more", "syllables": ["more"], "ipa": "/mɔːr/", "meaning": "adj.adv. 更多" },
    { "level": 3, "word": "most", "syllables": ["most"], "ipa": "/moʊst/", "meaning": "adj.adv. 大部分的" },
    { "level": 3, "word": "motorcycle", "syllables": ["mo", "tor", "cy", "cle"], "ipa": "/ˈmoʊtərsaɪkl/", "meaning": "n. 摩托車" },
    { "level": 3, "word": "mountain", "syllables": ["moun", "tain"], "ipa": "/ˈmaʊntn/", "meaning": "n. 山" },
    { "level": 3, "word": "myself", "syllables": ["my", "self"], "ipa": "/maɪˈself/", "meaning": "pron. 我自己" },
    { "level": 3, "word": "near", "syllables": ["near"], "ipa": "/nɪr/", "meaning": "prep. 靠近" },
    { "level": 3, "word": "news", "syllables": ["news"], "ipa": "/nuːz/", "meaning": "n. 新聞" },
    { "level": 3, "word": "next", "syllables": ["next"], "ipa": "/nekst/", "meaning": "adj. 下一個" },
    { "level": 3, "word": "nobody", "syllables": ["no", "bod", "y"], "ipa": "/ˈnoʊbədi/", "meaning": "pron. 沒有人" },
    { "level": 3, "word": "nothing", "syllables": ["noth", "ing"], "ipa": "/ˈnʌθɪŋ/", "meaning": "pron. 沒有東西" },
    { "level": 3, "word": "off", "syllables": ["off"], "ipa": "/ɔːf/", "meaning": "adv. 離開" },
    { "level": 3, "word": "oil", "syllables": ["oil"], "ipa": "/ɔɪl/", "meaning": "n. 油" },
    { "level": 3, "word": "only", "syllables": ["on", "ly"], "ipa": "/ˈoʊnli/", "meaning": "adv. 只有" },
    { "level": 3, "word": "or", "syllables": ["or"], "ipa": "/ɔːr/", "meaning": "conj. 或者" },
    { "level": 3, "word": "order", "syllables": ["or", "der"], "ipa": "/ˈɔːrdər/", "meaning": "n. 順序" },
    { "level": 3, "word": "other", "syllables": ["oth", "er"], "ipa": "/ˈʌðər/", "meaning": "adj. 其他的" },
    { "level": 3, "word": "ours", "syllables": ["ours"], "ipa": "/ˈaʊərz/", "meaning": "pron. 我們的" },
    { "level": 3, "word": "outside", "syllables": ["out", "side"], "ipa": "/ˌaʊtˈsaɪd/", "meaning": "adv. 在外面" },
    { "level": 3, "word": "paint", "syllables": ["paint"], "ipa": "/peɪnt/", "meaning": "v. 畫畫" },
    { "level": 3, "word": "parent", "syllables": ["par", "ent"], "ipa": "/ˈperənt/", "meaning": "n. 雙親之一" },
    { "level": 3, "word": "pay", "syllables": ["pay"], "ipa": "/peɪ/", "meaning": "v. 付錢" },
    { "level": 3, "word": "people", "syllables": ["peo", "ple"], "ipa": "/ˈpiːpl/", "meaning": "n. 人們" },
    { "level": 3, "word": "pet", "syllables": ["pet"], "ipa": "/pet/", "meaning": "n. 寵物" },
    { "level": 3, "word": "piano", "syllables": ["pi", "an", "o"], "ipa": "/piˈænoʊ/", "meaning": "n. 鋼琴" },
    { "level": 3, "word": "picnic", "syllables": ["pic", "nic"], "ipa": "/ˈpɪknɪk/", "meaning": "n. 野餐" },
    { "level": 3, "word": "place", "syllables": ["place"], "ipa": "/pleɪs/", "meaning": "n. 地方" },
    { "level": 3, "word": "plan", "syllables": ["plan"], "ipa": "/plæn/", "meaning": "n. 計劃" },
    { "level": 3, "word": "post", "syllables": ["post"], "ipa": "/poʊst/", "meaning": "v.n. 郵寄；柱子" },
    { "level": 3, "word": "postcard", "syllables": ["post", "card"], "ipa": "/ˈpoʊstkɑːrd/", "meaning": "n. 明信片" },
    { "level": 3, "word": "present", "syllables": ["pres", "ent"], "ipa": "/ˈpreznt/", "meaning": "n. 禮物" },
    { "level": 3, "word": "pretty", "syllables": ["pret", "ty"], "ipa": "/ˈprɪti/", "meaning": "adj.adv. 漂亮的；相當" },
    { "level": 3, "word": "pull", "syllables": ["pull"], "ipa": "/pʊl/", "meaning": "v. 拉" },
    { "level": 3, "word": "push", "syllables": ["push"], "ipa": "/pʊʃ/", "meaning": "v. 推" },
    { "level": 3, "word": "quick", "syllables": ["quick"], "ipa": "/kwɪk/", "meaning": "adj. 快的" },
    { "level": 3, "word": "rainbow", "syllables": ["rain", "bow"], "ipa": "/ˈreɪnboʊ/", "meaning": "n. 彩虹" },
    { "level": 3, "word": "real", "syllables": ["real"], "ipa": "/riːəl/", "meaning": "adj. 真實的" },
    { "level": 3, "word": "restroom", "syllables": ["rest", "room"], "ipa": "/ˈrestruːm/", "meaning": "n. 廁所" },
    { "level": 3, "word": "rich", "syllables": ["rich"], "ipa": "/rɪtʃ/", "meaning": "adj. 富有的" },
    { "level": 3, "word": "right", "syllables": ["right"], "ipa": "/raɪt/", "meaning": "adj. 正確的；右邊的" },
    { "level": 3, "word": "round", "syllables": ["round"], "ipa": "/raʊnd/", "meaning": "adj. 圓的" },
    { "level": 3, "word": "safe", "syllables": ["safe"], "ipa": "/seɪf/", "meaning": "adj. 安全的" },
    { "level": 3, "word": "salt", "syllables": ["salt"], "ipa": "/sɔːlt/", "meaning": "n. 鹽" },
    { "level": 3, "word": "same", "syllables": ["same"], "ipa": "/seɪm/", "meaning": "adj. 相同的" },
    { "level": 3, "word": "sea", "syllables": ["sea"], "ipa": "/siː/", "meaning": "n. 海" },
    { "level": 3, "word": "second", "syllables": ["sec", "ond"], "ipa": "/ˈsekənd/", "meaning": "n. 第二；秒" },
    { "level": 3, "word": "shape", "syllables": ["shape"], "ipa": "/ʃeɪp/", "meaning": "n. 形狀" },
    { "level": 3, "word": "shy", "syllables": ["shy"], "ipa": "/ʃaɪ/", "meaning": "adj. 害羞的" },
    { "level": 3, "word": "simple", "syllables": ["sim", "ple"], "ipa": "/ˈsɪmpl/", "meaning": "adj. 簡單的" },
    { "level": 3, "word": "size", "syllables": ["size"], "ipa": "/saɪz/", "meaning": "n. 尺寸" },
    { "level": 3, "word": "slow", "syllables": ["slow"], "ipa": "/sloʊ/", "meaning": "adj. 慢的" },
    { "level": 3, "word": "smart", "syllables": ["smart"], "ipa": "/smɑːrt/", "meaning": "adj. 聰明的" },
    { "level": 3, "word": "smell", "syllables": ["smell"], "ipa": "/smel/", "meaning": "v.n. 聞；味道" },
    { "level": 3, "word": "smile", "syllables": ["smile"], "ipa": "/smaɪl/", "meaning": "v.n. 微笑" },
    { "level": 3, "word": "snack", "syllables": ["snack"], "ipa": "/snæk/", "meaning": "n. 點心" },
    { "level": 3, "word": "so", "syllables": ["so"], "ipa": "/soʊ/", "meaning": "adv. 如此" },
    { "level": 3, "word": "some", "syllables": ["some"], "ipa": "/sʌm/", "meaning": "adj. 一些" },
    { "level": 3, "word": "somebody", "syllables": ["some", "bod", "y"], "ipa": "/ˈsʌmbədi/", "meaning": "pron. 某人" },
    { "level": 3, "word": "someone", "syllables": ["some", "one"], "ipa": "/ˈsʌmwʌn/", "meaning": "pron. 某人" },
    { "level": 3, "word": "something", "syllables": ["some", "thing"], "ipa": "/ˈsʌmθɪŋ/", "meaning": "pron. 某物" },
    { "level": 3, "word": "son", "syllables": ["son"], "ipa": "/sʌn/", "meaning": "n. 兒子" },
    { "level": 3, "word": "soon", "syllables": ["soon"], "ipa": "/suːn/", "meaning": "adv. 很快地" },
    { "level": 3, "word": "speak", "syllables": ["speak"], "ipa": "/spiːk/", "meaning": "v. 說" },
    { "level": 3, "word": "sport", "syllables": ["sport"], "ipa": "/spɔːrt/", "meaning": "n. 運動" },
    { "level": 3, "word": "square", "syllables": ["square"], "ipa": "/skwer/", "meaning": "n. 正方形" },
    { "level": 3, "word": "start", "syllables": ["start"], "ipa": "/stɑːrt/", "meaning": "v. 開始" },
    { "level": 3, "word": "steak", "syllables": ["steak"], "ipa": "/steɪk/", "meaning": "n. 牛排" },
    { "level": 3, "word": "stomach", "syllables": ["stom", "ach"], "ipa": "/ˈstʌmək/", "meaning": "n. 胃" },
    { "level": 3, "word": "story", "syllables": ["sto", "ry"], "ipa": "/ˈstɔːri/", "meaning": "n. 故事" },
    { "level": 3, "word": "study", "syllables": ["stud", "y"], "ipa": "/ˈstʌdi/", "meaning": "v. 研讀" },
    { "level": 3, "word": "stupid", "syllables": ["stu", "pid"], "ipa": "/ˈstuːpɪd/", "meaning": "adj. 笨的" },
    { "level": 3, "word": "supermarket", "syllables": ["su", "per", "mar", "ket"], "ipa": "/ˈsuːpərmɑːrkɪt/", "meaning": "n. 超級市場" },
    { "level": 3, "word": "sure", "syllables": ["sure"], "ipa": "/ʃʊr/", "meaning": "adj. 確定的" },
    { "level": 3, "word": "surprise", "syllables": ["sur", "prise"], "ipa": "/səˈpraɪz/", "meaning": "v.n. 驚訝" },
    { "level": 3, "word": "Taiwan", "syllables": ["Tai", "wan"], "ipa": "/ˌtaɪˈwɑːn/", "meaning": "n. 台灣" },
    { "level": 3, "word": "take", "syllables": ["take"], "ipa": "/teɪk/", "meaning": "v. 拿取" },
    { "level": 3, "word": "tape", "syllables": ["tape"], "ipa": "/teɪp/", "meaning": "n. 膠帶" },
    { "level": 3, "word": "taste", "syllables": ["taste"], "ipa": "/teɪst/", "meaning": "v. 品嚐" },
    { "level": 3, "word": "team", "syllables": ["team"], "ipa": "/tiːm/", "meaning": "n. 團隊" },
    { "level": 3, "word": "tell", "syllables": ["tell"], "ipa": "/tel/", "meaning": "v. 告訴" },
    { "level": 3, "word": "test", "syllables": ["test"], "ipa": "/test/", "meaning": "n. 測試" },
    { "level": 3, "word": "theater", "syllables": ["the", "a", "ter"], "ipa": "/ˈθiːətər/", "meaning": "n. 戲院" },
    { "level": 3, "word": "themselves", "syllables": ["them", "selves"], "ipa": "/ðəmˈselvz/", "meaning": "pron. 他們自己" },
    { "level": 3, "word": "then", "syllables": ["then"], "ipa": "/ðen/", "meaning": "adv. 那時" },
    { "level": 3, "word": "thing", "syllables": ["thing"], "ipa": "/θɪŋ/", "meaning": "n. 事物" },
    { "level": 3, "word": "think", "syllables": ["think"], "ipa": "/θɪŋk/", "meaning": "v. 想" },
    { "level": 3, "word": "third", "syllables": ["third"], "ipa": "/θɜːrd/", "meaning": "adj. 第三" },
    { "level": 3, "word": "thirsty", "syllables": ["thirst", "y"], "ipa": "/ˈθɜːrsti/", "meaning": "adj. 口渴的" },
    { "level": 3, "word": "thousand", "syllables": ["thou", "sand"], "ipa": "/ˈθaʊznd/", "meaning": "num. 千" },
    { "level": 3, "word": "ticket", "syllables": ["tick", "et"], "ipa": "/ˈtɪkɪt/", "meaning": "n. 票" },
    { "level": 3, "word": "tired", "syllables": ["tired"], "ipa": "/ˈtaɪərd/", "meaning": "adj. 累的" },
    { "level": 3, "word": "touch", "syllables": ["touch"], "ipa": "/tʌtʃ/", "meaning": "v. 觸摸" },
    { "level": 3, "word": "towel", "syllables": ["tow", "el"], "ipa": "/ˈtaʊəl/", "meaning": "n. 毛巾" },
    { "level": 3, "word": "toy", "syllables": ["toy"], "ipa": "/tɔɪ/", "meaning": "n. 玩具" },
    { "level": 3, "word": "traffic", "syllables": ["traf", "fic"], "ipa": "/ˈtræfɪk/", "meaning": "n. 交通" },
    { "level": 3, "word": "train", "syllables": ["train"], "ipa": "/treɪn/", "meaning": "n.v. 火車；訓練" },
    { "level": 3, "word": "trip", "syllables": ["trip"], "ipa": "/trɪp/", "meaning": "n. 旅程" },
    { "level": 3, "word": "TRUE", "syllables": ["TRUE"], "ipa": "/truː/", "meaning": "adj. 真實的" },
    { "level": 3, "word": "try", "syllables": ["try"], "ipa": "/traɪ/", "meaning": "v. 嘗試" },
    { "level": 3, "word": "typhoon", "syllables": ["ty", "phoon"], "ipa": "/taɪˈfuːn/", "meaning": "n. 颱風" },
    { "level": 3, "word": "understand", "syllables": ["un", "der", "stand"], "ipa": "/ˌʌndərˈstænd/", "meaning": "v. 了解" },
    { "level": 3, "word": "uniform", "syllables": ["u", "ni", "form"], "ipa": "/ˈjuːnɪfɔːrm/", "meaning": "n. 制服" },
    { "level": 3, "word": "up", "syllables": ["up"], "ipa": "/ʌp/", "meaning": "adv. 向上" },
    { "level": 3, "word": "us", "syllables": ["us"], "ipa": "/ʌs/", "meaning": "pron. 我們" },
    { "level": 3, "word": "USA", "syllables": ["USA"], "ipa": "/ˌjuː es ˈeɪ/", "meaning": "n. 美國" },
    { "level": 3, "word": "use", "syllables": ["use"], "ipa": "/juːz/", "meaning": "v. 使用" },
    { "level": 3, "word": "usually", "syllables": ["u", "su", "al", "ly"], "ipa": "/ˈjuːʒuəli/", "meaning": "adv. 通常" },
    { "level": 3, "word": "very", "syllables": ["ver", "y"], "ipa": "/ˈveri/", "meaning": "adv. 非常" },
    { "level": 3, "word": "wait", "syllables": ["wait"], "ipa": "/weɪt/", "meaning": "v. 等待" },
    { "level": 3, "word": "wash", "syllables": ["wash"], "ipa": "/wɑːʃ/", "meaning": "v. 洗" },
    { "level": 3, "word": "wet", "syllables": ["wet"], "ipa": "/wet/", "meaning": "adj. 濕的" },
    { "level": 3, "word": "where", "syllables": ["where"], "ipa": "/wer/", "meaning": "adv. 在哪裡" },
    { "level": 3, "word": "which", "syllables": ["which"], "ipa": "/wɪtʃ/", "meaning": "pron. 哪一個" },
    { "level": 3, "word": "why", "syllables": ["why"], "ipa": "/waɪ/", "meaning": "adv. 為什麼" },
    { "level": 3, "word": "wind", "syllables": ["wind"], "ipa": "/wɪnd/", "meaning": "n. 風" },
    { "level": 3, "word": "woman", "syllables": ["wom", "an"], "ipa": "/ˈwʊmən/", "meaning": "n. 女人" },
    { "level": 3, "word": "wonderful", "syllables": ["won", "der", "ful"], "ipa": "/ˈwʌndərfl/", "meaning": "adj. 美好的" },
    { "level": 3, "word": "worker", "syllables": ["work", "er"], "ipa": "/ˈwɜːrkər/", "meaning": "n. 工人" },
    { "level": 3, "word": "writer", "syllables": ["writ", "er"], "ipa": "/ˈraɪtər/", "meaning": "n. 作家" },
    { "level": 3, "word": "wrong", "syllables": ["wrong"], "ipa": "/rɔːŋ/", "meaning": "adj. 錯誤的" },
    { "level": 3, "word": "yeah", "syllables": ["yeah"], "ipa": "/jeə/", "meaning": "adv. 是啊" },
    { "level": 3, "word": "young", "syllables": ["young"], "ipa": "/jʌŋ/", "meaning": "adj. 年輕的" },
    { "level": 3, "word": "yourself", "syllables": ["your", "self"], "ipa": "/jʊərˈself/", "meaning": "pron. 你自己" },

    // === Level 4 ===
    { "level": 4, "word": "above", "syllables": ["a", "bove"], "ipa": "/əˈbʌv/", "meaning": "prep. 在...之上" },
    { "level": 4, "word": "across", "syllables": ["a", "cross"], "ipa": "/əˈkrɔːs/", "meaning": "prep. 跨越" },
    { "level": 4, "word": "actor", "syllables": ["ac", "tor"], "ipa": "/ˈæktər/", "meaning": "n. 男演員" },
    { "level": 4, "word": "actress", "syllables": ["ac", "tress"], "ipa": "/ˈæktrəs/", "meaning": "n. 女演員" },
    { "level": 4, "word": "airline", "syllables": ["air", "line"], "ipa": "/ˈerlaɪn/", "meaning": "n. 航空公司" },
    { "level": 4, "word": "alarm", "syllables": ["a", "larm"], "ipa": "/əˈlɑːrm/", "meaning": "n. 鬧鐘" },
    { "level": 4, "word": "along", "syllables": ["a", "long"], "ipa": "/əˈlɔːŋ/", "meaning": "prep. 沿著" },
    { "level": 4, "word": "also", "syllables": ["al", "so"], "ipa": "/ˈɔːlsoʊ/", "meaning": "adv. 也" },
    { "level": 4, "word": "always", "syllables": ["al", "ways"], "ipa": "/ˈɔːlweɪz/", "meaning": "adv. 總是" },
    { "level": 4, "word": "among", "syllables": ["a", "mong"], "ipa": "/əˈmʌŋ/", "meaning": "prep. 在...之中" },
    { "level": 4, "word": "angel", "syllables": ["an", "gel"], "ipa": "/ˈeɪndʒl/", "meaning": "n. 天使" },
    { "level": 4, "word": "ankle", "syllables": ["an", "kle"], "ipa": "/ˈæŋkl/", "meaning": "n. 腳踝" },
    { "level": 4, "word": "ant", "syllables": ["ant"], "ipa": "/ænt/", "meaning": "n. 螞蟻" },
    { "level": 4, "word": "apartment", "syllables": ["a", "part", "ment"], "ipa": "/əˈpɑːrtmənt/", "meaning": "n. 公寓" },
    { "level": 4, "word": "armchair", "syllables": ["arm", "chair"], "ipa": "/ˈɑːrmtʃer/", "meaning": "n. 扶手椅" },
    { "level": 4, "word": "artist", "syllables": ["ar", "tist"], "ipa": "/ˈɑːrtɪst/", "meaning": "n. 藝術家" },
    { "level": 4, "word": "balloon", "syllables": ["bal", "loon"], "ipa": "/bəˈluːn/", "meaning": "n. 氣球" },
    { "level": 4, "word": "barber", "syllables": ["bar", "ber"], "ipa": "/ˈbɑːrbər/", "meaning": "n. 理髮師" },
    { "level": 4, "word": "bat", "syllables": ["bat"], "ipa": "/bæt/", "meaning": "n. 球棒；蝙蝠" },
    { "level": 4, "word": "bean", "syllables": ["bean"], "ipa": "/biːn/", "meaning": "n. 豆子" },
    { "level": 4, "word": "begin", "syllables": ["be", "gin"], "ipa": "/bɪˈɡɪn/", "meaning": "v. 開始" },
    { "level": 4, "word": "believe", "syllables": ["be", "lieve"], "ipa": "/bɪˈliːv/", "meaning": "v. 相信" },
    { "level": 4, "word": "below", "syllables": ["be", "low"], "ipa": "/bɪˈloʊ/", "meaning": "prep. 在...下面" },
    { "level": 4, "word": "beside", "syllables": ["be", "side"], "ipa": "/bɪˈsaɪd/", "meaning": "prep. 在...旁邊" },
    { "level": 4, "word": "besides", "syllables": ["be", "sides"], "ipa": "/bɪˈsaɪdz/", "meaning": "adv.prep. 此外" },
    { "level": 4, "word": "best", "syllables": ["best"], "ipa": "/best/", "meaning": "adj.adv. 最好的" },
    { "level": 4, "word": "better", "syllables": ["bet", "ter"], "ipa": "/ˈbetər/", "meaning": "adj.adv. 更好的" },
    { "level": 4, "word": "beyond", "syllables": ["be", "yond"], "ipa": "/bɪˈjɑːnd/", "meaning": "prep. 在...之外" },
    { "level": 4, "word": "bite", "syllables": ["bite"], "ipa": "/baɪt/", "meaning": "v. 咬" },
    { "level": 4, "word": "blanket", "syllables": ["blan", "ket"], "ipa": "/ˈblæŋkɪt/", "meaning": "n. 毛毯" },
    { "level": 4, "word": "blow", "syllables": ["blow"], "ipa": "/bloʊ/", "meaning": "v. 吹" },
    { "level": 4, "word": "bored", "syllables": ["bored"], "ipa": "/bɔːrd/", "meaning": "adj. 感到無聊的" },
    { "level": 4, "word": "borrow", "syllables": ["bor", "row"], "ipa": "/ˈbɑːroʊ/", "meaning": "v. 借" },
    { "level": 4, "word": "bottom", "syllables": ["bot", "tom"], "ipa": "/ˈbɑːtəm/", "meaning": "n. 底部" },
    { "level": 4, "word": "break", "syllables": ["break"], "ipa": "/breɪk/", "meaning": "v.n. 打破；休息" },
    { "level": 4, "word": "bring", "syllables": ["bring"], "ipa": "/brɪŋ/", "meaning": "v. 帶來" },
    { "level": 4, "word": "bucket", "syllables": ["buck", "et"], "ipa": "/ˈbʌkɪt/", "meaning": "n. 水桶" },
    { "level": 4, "word": "business", "syllables": ["bus", "i", "ness"], "ipa": "/ˈbɪznəs/", "meaning": "n. 生意" },
    { "level": 4, "word": "butterfly", "syllables": ["but", "ter", "fly"], "ipa": "/ˈbʌtərflaɪ/", "meaning": "n. 蝴蝶" },
    { "level": 4, "word": "cabbage", "syllables": ["cab", "bage"], "ipa": "/ˈkæbɪdʒ/", "meaning": "n. 高麗菜" },
    { "level": 4, "word": "camera", "syllables": ["cam", "er", "a"], "ipa": "/ˈkæmrə/", "meaning": "n. 照相機" },
    { "level": 4, "word": "camp", "syllables": ["camp"], "ipa": "/kæmp/", "meaning": "v.n. 露營" },
    { "level": 4, "word": "care", "syllables": ["care"], "ipa": "/ker/", "meaning": "v. 關心" },
    { "level": 4, "word": "careful", "syllables": ["care", "ful"], "ipa": "/ˈkerfl/", "meaning": "adj. 小心的" },
    { "level": 4, "word": "carry", "syllables": ["car", "ry"], "ipa": "/ˈkæri/", "meaning": "v. 搬運" },
    { "level": 4, "word": "change", "syllables": ["change"], "ipa": "/tʃeɪndʒ/", "meaning": "v.n. 改變；零錢" },
    { "level": 4, "word": "choose", "syllables": ["choose"], "ipa": "/tʃuːz/", "meaning": "v. 選擇" },
    { "level": 4, "word": "church", "syllables": ["church"], "ipa": "/tʃɜːrtʃ/", "meaning": "n. 教堂" },
    { "level": 4, "word": "clerk", "syllables": ["clerk"], "ipa": "/klɜːrk/", "meaning": "n. 店員" },
    { "level": 4, "word": "climb", "syllables": ["climb"], "ipa": "/klaɪm/", "meaning": "v. 爬" },
    { "level": 4, "word": "cockroach", "syllables": ["cock", "roach"], "ipa": "/ˈkɑːkroʊtʃ/", "meaning": "n. 蟑螂" },
    { "level": 4, "word": "collect", "syllables": ["col", "lect"], "ipa": "/kəˈlekt/", "meaning": "v. 收集" },
    { "level": 4, "word": "comfortable", "syllables": ["com", "fort", "a", "ble"], "ipa": "/ˈkʌmftəbl/", "meaning": "adj. 舒適的" },
    { "level": 4, "word": "comic", "syllables": ["com", "ic"], "ipa": "/ˈkɑːmɪk/", "meaning": "n. 漫畫" },
    { "level": 4, "word": "copy", "syllables": ["cop", "y"], "ipa": "/ˈkɑːpi/", "meaning": "v. 複印" },
    { "level": 4, "word": "corn", "syllables": ["corn"], "ipa": "/kɔːrn/", "meaning": "n. 玉米" },
    { "level": 4, "word": "correct", "syllables": ["cor", "rect"], "ipa": "/kəˈrekt/", "meaning": "adj. 正確的" },
    { "level": 4, "word": "cost", "syllables": ["cost"], "ipa": "/kɔːst/", "meaning": "v. 花費" },
    { "level": 4, "word": "cough", "syllables": ["cough"], "ipa": "/kɔːf/", "meaning": "v. 咳嗽" },
    { "level": 4, "word": "could", "syllables": ["could"], "ipa": "/kəd/", "meaning": "aux. 能夠" },
    { "level": 4, "word": "count", "syllables": ["count"], "ipa": "/kaʊnt/", "meaning": "v. 數數" },
    { "level": 4, "word": "cousin", "syllables": ["cou", "sin"], "ipa": "/ˈkʌzn/", "meaning": "n. 堂/表兄弟姊妹" },
    { "level": 4, "word": "crab", "syllables": ["crab"], "ipa": "/kræb/", "meaning": "n. 螃蟹" },
    { "level": 4, "word": "cross", "syllables": ["cross"], "ipa": "/krɔːs/", "meaning": "v.n. 越過；十字" },
    { "level": 4, "word": "danger", "syllables": ["dan", "ger"], "ipa": "/ˈdeɪndʒər/", "meaning": "n. 危險" },
    { "level": 4, "word": "dangerous", "syllables": ["dan", "ger", "ous"], "ipa": "/ˈdeɪndʒərəs/", "meaning": "adj. 危險的" },
    { "level": 4, "word": "date", "syllables": ["date"], "ipa": "/deɪt/", "meaning": "n. 日期" },
    { "level": 4, "word": "dead", "syllables": ["dead"], "ipa": "/ded/", "meaning": "adj. 死的" },
    { "level": 4, "word": "dear", "syllables": ["dear"], "ipa": "/dɪr/", "meaning": "adj. 親愛的" },
    { "level": 4, "word": "death", "syllables": ["death"], "ipa": "/deθ/", "meaning": "n. 死亡" },
    { "level": 4, "word": "deep", "syllables": ["deep"], "ipa": "/diːp/", "meaning": "adj. 深的" },
    { "level": 4, "word": "dictionary", "syllables": ["dic", "tion", "ar", "y"], "ipa": "/ˈdɪkʃəneri/", "meaning": "n. 字典" },
    { "level": 4, "word": "die", "syllables": ["die"], "ipa": "/daɪ/", "meaning": "v. 死亡" },
    { "level": 4, "word": "discuss", "syllables": ["dis", "cuss"], "ipa": "/dɪˈskʌs/", "meaning": "v. 討論" },
    { "level": 4, "word": "draw", "syllables": ["draw"], "ipa": "/drɔː/", "meaning": "v. 畫" },
    { "level": 4, "word": "earth", "syllables": ["earth"], "ipa": "/ɜːrθ/", "meaning": "n. 地球" },
    { "level": 4, "word": "east", "syllables": ["east"], "ipa": "/iːst/", "meaning": "n.adj. 東方" },
    { "level": 4, "word": "either", "syllables": ["ei", "ther"], "ipa": "/ˈiːðər/", "meaning": "adj.adv. 任一；也不" },
    { "level": 4, "word": "enjoy", "syllables": ["en", "joy"], "ipa": "/ɪnˈdʒɔɪ/", "meaning": "v. 享受" },
    { "level": 4, "word": "enter", "syllables": ["en", "ter"], "ipa": "/ˈentər/", "meaning": "v. 進入" },
    { "level": 4, "word": "even", "syllables": ["e", "ven"], "ipa": "/ˈiːvn/", "meaning": "adv. 甚至" },
    { "level": 4, "word": "example", "syllables": ["ex", "am", "ple"], "ipa": "/ɪɡˈzæmpl/", "meaning": "n. 例子" },
    { "level": 4, "word": "except", "syllables": ["ex", "cept"], "ipa": "/ɪkˈsept/", "meaning": "prep. 除了...之外" },
    { "level": 4, "word": "expensive", "syllables": ["ex", "pen", "sive"], "ipa": "/ɪkˈspensɪv/", "meaning": "adj. 昂貴的" },
    { "level": 4, "word": "experience", "syllables": ["ex", "pe", "ri", "ence"], "ipa": "/ɪkˈspɪriəns/", "meaning": "n. 經驗" },
    { "level": 4, "word": "fact", "syllables": ["fact"], "ipa": "/fækt/", "meaning": "n. 事實" },
    { "level": 4, "word": "factory", "syllables": ["fac", "to", "ry"], "ipa": "/ˈfæktri/", "meaning": "n. 工廠" },
    { "level": 4, "word": "fall", "syllables": ["fall"], "ipa": "/fɔːl/", "meaning": "v. 落下" },
    { "level": 4, "word": "fan", "syllables": ["fan"], "ipa": "/fæn/", "meaning": "n. 風扇；迷" },
    { "level": 4, "word": "fill", "syllables": ["fill"], "ipa": "/fɪl/", "meaning": "v. 填滿" },
    { "level": 4, "word": "finally", "syllables": ["fi", "nal", "ly"], "ipa": "/ˈfaɪnəli/", "meaning": "adv. 終於" },
    { "level": 4, "word": "finish", "syllables": ["fin", "ish"], "ipa": "/ˈfɪnɪʃ/", "meaning": "v. 完成" },
    { "level": 4, "word": "fix", "syllables": ["fix"], "ipa": "/fɪks/", "meaning": "v. 修理" },
    { "level": 4, "word": "follow", "syllables": ["fol", "low"], "ipa": "/ˈfɑːloʊ/", "meaning": "v. 跟隨" },
    { "level": 4, "word": "forget", "syllables": ["for", "get"], "ipa": "/fərˈɡet/", "meaning": "v. 忘記" },
    { "level": 4, "word": "fox", "syllables": ["fox"], "ipa": "/fɑːks/", "meaning": "n. 狐狸" },
    { "level": 4, "word": "friendly", "syllables": ["friend", "ly"], "ipa": "/ˈfrendli/", "meaning": "adj. 友好的" },
    { "level": 4, "word": "frog", "syllables": ["frog"], "ipa": "/frɔːɡ/", "meaning": "n. 青蛙" },
    { "level": 4, "word": "fry", "syllables": ["fry"], "ipa": "/fraɪ/", "meaning": "v. 炸" },
    { "level": 4, "word": "garbage", "syllables": ["gar", "bage"], "ipa": "/ˈɡɑːrbɪdʒ/", "meaning": "n. 垃圾" },
    { "level": 4, "word": "gas", "syllables": ["gas"], "ipa": "/ɡæs/", "meaning": "n. 瓦斯" },
    { "level": 4, "word": "glue", "syllables": ["glue"], "ipa": "/ɡluː/", "meaning": "n. 膠水" },
    { "level": 4, "word": "gold", "syllables": ["gold"], "ipa": "/ɡoʊld/", "meaning": "n. 金子" },
    { "level": 4, "word": "granddaughter", "syllables": ["grand", "daugh", "ter"], "ipa": "/ˈɡrændɔːtər/", "meaning": "n. 孫女" },
    { "level": 4, "word": "grandson", "syllables": ["grand", "son"], "ipa": "/ˈɡrændsʌn/", "meaning": "n. 孫子" },
    { "level": 4, "word": "ground", "syllables": ["ground"], "ipa": "/ɡraʊnd/", "meaning": "n. 地面" },
    { "level": 4, "word": "grow", "syllables": ["grow"], "ipa": "/ɡroʊ/", "meaning": "v. 生長" },
    { "level": 4, "word": "guess", "syllables": ["guess"], "ipa": "/ɡes/", "meaning": "v. 猜測" },
    { "level": 4, "word": "habit", "syllables": ["hab", "it"], "ipa": "/ˈhæbɪt/", "meaning": "n. 習慣" },
    { "level": 4, "word": "hand", "syllables": ["hand"], "ipa": "/hænd/", "meaning": "v. 遞" },
    { "level": 4, "word": "happen", "syllables": ["hap", "pen"], "ipa": "/ˈhæpən/", "meaning": "v. 發生" },
    { "level": 4, "word": "hate", "syllables": ["hate"], "ipa": "/heɪt/", "meaning": "v. 討厭" },
    { "level": 4, "word": "headache", "syllables": ["head", "ache"], "ipa": "/ˈhedeɪk/", "meaning": "n. 頭痛" },
    { "level": 4, "word": "health", "syllables": ["health"], "ipa": "/helθ/", "meaning": "n. 健康" },
    { "level": 4, "word": "healthy", "syllables": ["health", "y"], "ipa": "/ˈhelθi/", "meaning": "adj. 健康的" },
    { "level": 4, "word": "heat", "syllables": ["heat"], "ipa": "/hiːt/", "meaning": "n. 熱" },
    { "level": 4, "word": "hide", "syllables": ["hide"], "ipa": "/haɪd/", "meaning": "v. 躲藏" },
    { "level": 4, "word": "however", "syllables": ["how", "ev", "er"], "ipa": "/haʊˈevər/", "meaning": "adv. 然而" },
    { "level": 4, "word": "hurry", "syllables": ["hur", "ry"], "ipa": "/ˈhɜːri/", "meaning": "v. 趕快" },
    { "level": 4, "word": "hurt", "syllables": ["hurt"], "ipa": "/hɜːrt/", "meaning": "v. 受傷" },
    { "level": 4, "word": "husband", "syllables": ["hus", "band"], "ipa": "/ˈhʌzbənd/", "meaning": "n. 丈夫" },
    { "level": 4, "word": "interest", "syllables": ["in", "ter", "est"], "ipa": "/ˈɪntrest/", "meaning": "n. 興趣" },
    { "level": 4, "word": "jog", "syllables": ["jog"], "ipa": "/dʒɑːɡ/", "meaning": "v. 慢跑" },
    { "level": 4, "word": "join", "syllables": ["join"], "ipa": "/dʒɔɪn/", "meaning": "v. 參加" },
    { "level": 4, "word": "joy", "syllables": ["joy"], "ipa": "/dʒɔɪ/", "meaning": "n. 喜悅" },
    { "level": 4, "word": "ketchup", "syllables": ["ketch", "up"], "ipa": "/ˈketʃəp/", "meaning": "n. 番茄醬" },
    { "level": 4, "word": "kick", "syllables": ["kick"], "ipa": "/kɪk/", "meaning": "v. 踢" },
    { "level": 4, "word": "kid", "syllables": ["kid"], "ipa": "/kɪd/", "meaning": "n. 小孩" },
    { "level": 4, "word": "kill", "syllables": ["kill"], "ipa": "/kɪl/", "meaning": "v. 殺死" },
    { "level": 4, "word": "kind", "syllables": ["kind"], "ipa": "/kaɪnd/", "meaning": "adj. 仁慈的" },
    { "level": 4, "word": "knock", "syllables": ["knock"], "ipa": "/nɑːk/", "meaning": "v. 敲" },
    { "level": 4, "word": "language", "syllables": ["lan", "guage"], "ipa": "/ˈlæŋɡwɪdʒ/", "meaning": "n. 語言" },
    { "level": 4, "word": "large", "syllables": ["large"], "ipa": "/lɑːrdʒ/", "meaning": "adj. 大的" },
    { "level": 4, "word": "last", "syllables": ["last"], "ipa": "/læst/", "meaning": "adj. 最後的" },
    { "level": 4, "word": "laugh", "syllables": ["laugh"], "ipa": "/læf/", "meaning": "v. 笑" },
    { "level": 4, "word": "lend", "syllables": ["lend"], "ipa": "/lend/", "meaning": "v. 借出" },
    { "level": 4, "word": "less", "syllables": ["less"], "ipa": "/les/", "meaning": "adj.adv. 較少的" },
    { "level": 4, "word": "lie", "syllables": ["lie"], "ipa": "/laɪ/", "meaning": "v. 躺下；說謊" },
    { "level": 4, "word": "line", "syllables": ["line"], "ipa": "/laɪn/", "meaning": "n. 線" },
    { "level": 4, "word": "loud", "syllables": ["loud"], "ipa": "/laʊd/", "meaning": "adj. 大聲的" },
    { "level": 4, "word": "machine", "syllables": ["ma", "chine"], "ipa": "/məˈʃiːn/", "meaning": "n. 機器" },
    { "level": 4, "word": "magic", "syllables": ["ma", "gic"], "ipa": "/ˈmædʒɪk/", "meaning": "n.adj. 魔術" },
    { "level": 4, "word": "many", "syllables": ["man", "y"], "ipa": "/ˈmeni/", "meaning": "adj. 許多的" },
    { "level": 4, "word": "map", "syllables": ["map"], "ipa": "/mæp/", "meaning": "n. 地圖" },
    { "level": 4, "word": "may", "syllables": ["may"], "ipa": "/meɪ/", "meaning": "aux. 可能" },
    { "level": 4, "word": "maybe", "syllables": ["may", "be"], "ipa": "/ˈmeɪbi/", "meaning": "adv. 也許" },
    { "level": 4, "word": "meal", "syllables": ["meal"], "ipa": "/miːl/", "meaning": "n. 餐" },
    { "level": 2, "word": "medicine", "syllables": ["med", "i", "cine"], "ipa": "/ˈmedsn/", "meaning": "n. 藥" },
    { "level": 4, "word": "medium", "syllables": ["me", "di", "um"], "ipa": "/ˈmiːdiəm/", "meaning": "adj. 中等的" },
    { "level": 4, "word": "mind", "syllables": ["mind"], "ipa": "/maɪnd/", "meaning": "v.n. 介意；心智" },
    { "level": 4, "word": "mistake", "syllables": ["mis", "take"], "ipa": "/mɪˈsteɪk/", "meaning": "n. 錯誤" },
    { "level": 4, "word": "moment", "syllables": ["mo", "ment"], "ipa": "/ˈmoʊmənt/", "meaning": "n. 片刻" },
    { "level": 4, "word": "must", "syllables": ["must"], "ipa": "/mʌst/", "meaning": "aux. 必須" },
    { "level": 4, "word": "never", "syllables": ["nev", "er"], "ipa": "/ˈnevər/", "meaning": "adv. 從不" },
    { "level": 4, "word": "noise", "syllables": ["noise"], "ipa": "/nɔɪz/", "meaning": "n. 噪音" },
    { "level": 4, "word": "north", "syllables": ["north"], "ipa": "/nɔːrθ/", "meaning": "n. 北方" },
    { "level": 4, "word": "once", "syllables": ["once"], "ipa": "/wʌns/", "meaning": "adv. 一次" },
    { "level": 4, "word": "pack", "syllables": ["pack"], "ipa": "/pæk/", "meaning": "v. 打包" },
    { "level": 4, "word": "package", "syllables": ["pack", "age"], "ipa": "/ˈpækɪdʒ/", "meaning": "n. 包裹" },
    { "level": 4, "word": "pair", "syllables": ["pair"], "ipa": "/per/", "meaning": "n. 一雙" },
    { "level": 4, "word": "pass", "syllables": ["pass"], "ipa": "/pæs/", "meaning": "v. 通過" },
    { "level": 4, "word": "PE", "syllables": ["PE"], "ipa": "/ˌpiː ˈiː/", "meaning": "n. 體育" },
    { "level": 4, "word": "perhaps", "syllables": ["per", "haps"], "ipa": "/pərˈhæps/", "meaning": "adv. 或許" },
    { "level": 4, "word": "person", "syllables": ["per", "son"], "ipa": "/ˈpɜːrsn/", "meaning": "n. 人" },
    { "level": 4, "word": "pick", "syllables": ["pick"], "ipa": "/pɪk/", "meaning": "v. 挑選；撿" },
    { "level": 4, "word": "piece", "syllables": ["piece"], "ipa": "/piːs/", "meaning": "n. 一片" },
    { "level": 4, "word": "play", "syllables": ["play"], "ipa": "/pleɪ/", "meaning": "v. 玩" },
    { "level": 4, "word": "player", "syllables": ["play", "er"], "ipa": "/ˈpleɪər/", "meaning": "n. 選手" },
    { "level": 4, "word": "point", "syllables": ["point"], "ipa": "/pɔɪnt/", "meaning": "v. 指向" },
    { "level": 4, "word": "polite", "syllables": ["po", "lite"], "ipa": "/pəˈlaɪt/", "meaning": "adj. 禮貌的" },
    { "level": 4, "word": "poor", "syllables": ["poor"], "ipa": "/pʊr/", "meaning": "adj. 貧窮的" },
    { "level": 4, "word": "practice", "syllables": ["prac", "tice"], "ipa": "/ˈpræktɪs/", "meaning": "v. 練習" },
    { "level": 4, "word": "prepare", "syllables": ["pre", "pare"], "ipa": "/prɪˈper/", "meaning": "v. 準備" },
    { "level": 4, "word": "price", "syllables": ["price"], "ipa": "/praɪs/", "meaning": "n. 價格" },
    { "level": 4, "word": "problem", "syllables": ["prob", "lem"], "ipa": "/ˈprɑːbləm/", "meaning": "n. 問題" },
    { "level": 4, "word": "really", "syllables": ["re", "al", "ly"], "ipa": "/ˈriːəli/", "meaning": "adv. 真正地" },
    { "level": 4, "word": "refrigerator", "syllables": ["re", "frig", "er", "a", "tor"], "ipa": "/rɪˈfrɪdʒəreɪtər/", "meaning": "n. 冰箱" },
    { "level": 4, "word": "repeat", "syllables": ["re", "peat"], "ipa": "/rɪˈpiːt/", "meaning": "v. 重複" },
    { "level": 4, "word": "rest", "syllables": ["rest"], "ipa": "/rest/", "meaning": "v.n. 休息" },
    { "level": 4, "word": "ride", "syllables": ["ride"], "ipa": "/raɪd/", "meaning": "v. 騎" },
    { "level": 4, "word": "sale", "syllables": ["sale"], "ipa": "/seɪl/", "meaning": "n. 出售；特價" },
    { "level": 4, "word": "save", "syllables": ["save"], "ipa": "/seɪv/", "meaning": "v. 救；節省" },
    { "level": 4, "word": "seat", "syllables": ["seat"], "ipa": "/siːt/", "meaning": "n. 座位" },
    { "level": 4, "word": "seldom", "syllables": ["sel", "dom"], "ipa": "/ˈseldəm/", "meaning": "adv. 很少" },
    { "level": 4, "word": "send", "syllables": ["send"], "ipa": "/send/", "meaning": "v. 傳送；寄" },
    { "level": 4, "word": "several", "syllables": ["sev", "er", "al"], "ipa": "/ˈsevrəl/", "meaning": "adj. 幾個的" },
    { "level": 4, "word": "shall", "syllables": ["shall"], "ipa": "/ʃæl/", "meaning": "aux. 將要" },
    { "level": 4, "word": "ship", "syllables": ["ship"], "ipa": "/ʃɪp/", "meaning": "n. 船" },
    { "level": 4, "word": "should", "syllables": ["should"], "ipa": "/ʃəd/", "meaning": "aux. 應該" },
    { "level": 4, "word": "side", "syllables": ["side"], "ipa": "/saɪd/", "meaning": "n. 邊" },
    { "level": 4, "word": "since", "syllables": ["since"], "ipa": "/sɪns/", "meaning": "prep.conj. 自從" },
    { "level": 4, "word": "somewhere", "syllables": ["some", "where"], "ipa": "/ˈsʌmwer/", "meaning": "adv. 某處" },
    { "level": 4, "word": "south", "syllables": ["south"], "ipa": "/saʊθ/", "meaning": "n. 南方" },
    { "level": 4, "word": "special", "syllables": ["spe", "cial"], "ipa": "/ˈspeʃl/", "meaning": "adj. 特別的" },
    { "level": 4, "word": "spell", "syllables": ["spell"], "ipa": "/spel/", "meaning": "v. 拼字" },
    { "level": 4, "word": "spend", "syllables": ["spend"], "ipa": "/spend/", "meaning": "v. 花費" },
    { "level": 4, "word": "stay", "syllables": ["stay"], "ipa": "/steɪ/", "meaning": "v. 停留" },
    { "level": 4, "word": "still", "syllables": ["still"], "ipa": "/stɪl/", "meaning": "adv. 仍然" },
    { "level": 4, "word": "strange", "syllables": ["strange"], "ipa": "/streɪndʒ/", "meaning": "adj. 奇怪的" },
    { "level": 4, "word": "stranger", "syllables": ["stran", "ger"], "ipa": "/ˈstreɪndʒər/", "meaning": "n. 陌生人" },
    { "level": 4, "word": "successful", "syllables": ["suc", "cess", "ful"], "ipa": "/səkˈsesfl/", "meaning": "adj. 成功的" },
    { "level": 4, "word": "surprised", "syllables": ["sur", "prised"], "ipa": "/səˈpraɪzd/", "meaning": "adj. 感到驚訝的" },
    { "level": 4, "word": "teenager", "syllables": ["teen", "ag", "er"], "ipa": "/ˈtiːneɪdʒər/", "meaning": "n. 青少年" },
    { "level": 4, "word": "tennis", "syllables": ["ten", "nis"], "ipa": "/ˈtenɪs/", "meaning": "n. 網球" },
    { "level": 4, "word": "than", "syllables": ["than"], "ipa": "/ðæn/", "meaning": "conj. 比" },
    { "level": 4, "word": "trouble", "syllables": ["trou", "ble"], "ipa": "/ˈtrʌbl/", "meaning": "n. 麻煩" },
    { "level": 4, "word": "turn", "syllables": ["turn"], "ipa": "/tɜːrn/", "meaning": "v. 轉動" },
    { "level": 4, "word": "unhappy", "syllables": ["un", "hap", "py"], "ipa": "/ʌnˈhæpi/", "meaning": "adj. 不快樂的" },
    { "level": 4, "word": "very", "syllables": ["ver", "y"], "ipa": "/ˈveri/", "meaning": "adv. 非常" },
    { "level": 4, "word": "video", "syllables": ["vid", "e", "o"], "ipa": "/ˈvɪdioʊ/", "meaning": "n. 影片" },
    { "level": 4, "word": "voice", "syllables": ["voice"], "ipa": "/vɔɪs/", "meaning": "n. 聲音" },
    { "level": 4, "word": "wake", "syllables": ["wake"], "ipa": "/weɪk/", "meaning": "v. 醒來" },
    { "level": 4, "word": "wall", "syllables": ["wall"], "ipa": "/wɔːl/", "meaning": "n. 牆" },
    { "level": 4, "word": "way", "syllables": ["way"], "ipa": "/weɪ/", "meaning": "n. 路；方式" },
    { "level": 4, "word": "weak", "syllables": ["weak"], "ipa": "/wiːk/", "meaning": "adj. 虛弱的" },
    { "level": 4, "word": "wear", "syllables": ["wear"], "ipa": "/wer/", "meaning": "v. 穿戴" },
    { "level": 4, "word": "weekend", "syllables": ["week", "end"], "ipa": "/ˈwiːkend/", "meaning": "n. 週末" },
    { "level": 4, "word": "west", "syllables": ["west"], "ipa": "/west/", "meaning": "n. 西方" },
    { "level": 4, "word": "whatever", "syllables": ["what", "ev", "er"], "ipa": "/wətˈevər/", "meaning": "pron. 無論如何" },
    { "level": 4, "word": "when", "syllables": ["when"], "ipa": "/wen/", "meaning": "conj.adv. 當...時" },
    { "level": 4, "word": "whether", "syllables": ["wheth", "er"], "ipa": "/ˈweðər/", "meaning": "conj. 是否" },
    { "level": 4, "word": "who", "syllables": ["who"], "ipa": "/huː/", "meaning": "pron. 誰" },
    { "level": 4, "word": "whose", "syllables": ["whose"], "ipa": "/huːz/", "meaning": "pron. 誰的" },
    { "level": 4, "word": "wife", "syllables": ["wife"], "ipa": "/waɪf/", "meaning": "n. 妻子" },
    { "level": 4, "word": "will", "syllables": ["will"], "ipa": "/wɪl/", "meaning": "aux. 將會" },
    { "level": 4, "word": "wish", "syllables": ["wish"], "ipa": "/wɪʃ/", "meaning": "v.n. 希望" },
    { "level": 4, "word": "world", "syllables": ["world"], "ipa": "/wɜːrld/", "meaning": "n. 世界" },
    { "level": 4, "word": "would", "syllables": ["would"], "ipa": "/wʊd/", "meaning": "aux. 將會" },

    // === Level 5 ===
    { "level": 5, "word": "able", "syllables": ["a", "ble"], "ipa": "/ˈeɪbl/", "meaning": "adj. 有能力的" },
    { "level": 5, "word": "absent", "syllables": ["ab", "sent"], "ipa": "/ˈæbsənt/", "meaning": "adj. 缺席的" },
    { "level": 5, "word": "accident", "syllables": ["ac", "ci", "dent"], "ipa": "/ˈæksɪdənt/", "meaning": "n. 意外" },
    { "level": 5, "word": "active", "syllables": ["ac", "tive"], "ipa": "/ˈæktɪv/", "meaning": "adj. 活躍的" },
    { "level": 5, "word": "activity", "syllables": ["ac", "tiv", "i", "ty"], "ipa": "/ækˈtɪvəti/", "meaning": "n. 活動" },
    { "level": 5, "word": "address", "syllables": ["ad", "dress"], "ipa": "/ˈædres/", "meaning": "n. 地址" },
    { "level": 5, "word": "adult", "syllables": ["a", "dult"], "ipa": "/əˈdʌlt/", "meaning": "n. 成人" },
    { "level": 5, "word": "agree", "syllables": ["a", "gree"], "ipa": "/əˈɡriː/", "meaning": "v. 同意" },
    { "level": 5, "word": "alive", "syllables": ["a", "live"], "ipa": "/əˈlaɪv/", "meaning": "adj. 活著的" },
    { "level": 5, "word": "allow", "syllables": ["al", "low"], "ipa": "/əˈlaʊ/", "meaning": "v. 允許" },
    { "level": 5, "word": "already", "syllables": ["al", "read", "y"], "ipa": "/ɔːlˈredi/", "meaning": "adv. 已經" },
    { "level": 5, "word": "appear", "syllables": ["ap", "pear"], "ipa": "/əˈpɪr/", "meaning": "v. 出現" },
    { "level": 5, "word": "area", "syllables": ["ar", "ea"], "ipa": "/ˈeriə/", "meaning": "n. 區域" },
    { "level": 5, "word": "arrive", "syllables": ["ar", "rive"], "ipa": "/əˈraɪv/", "meaning": "v. 到達" },
    { "level": 5, "word": "away", "syllables": ["a", "way"], "ipa": "/əˈweɪ/", "meaning": "adv. 離開" },
    { "level": 5, "word": "become", "syllables": ["be", "come"], "ipa": "/bɪˈkʌm/", "meaning": "v. 變成" },
    { "level": 5, "word": "boring", "syllables": ["bor", "ing"], "ipa": "/ˈbɔːrɪŋ/", "meaning": "adj. 無聊的" },
    { "level": 5, "word": "bridge", "syllables": ["bridge"], "ipa": "/brɪdʒ/", "meaning": "n. 橋" },
    { "level": 5, "word": "building", "syllables": ["build", "ing"], "ipa": "/ˈbɪldɪŋ/", "meaning": "n. 建築物" },
    { "level": 5, "word": "businessman", "syllables": ["busi", "ness", "man"], "ipa": "/ˈbɪznəsmæn/", "meaning": "n. 商人" },
    { "level": 5, "word": "celebrate", "syllables": ["cel", "e", "brate"], "ipa": "/ˈselɪbreɪt/", "meaning": "v. 慶祝" },
    { "level": 5, "word": "centimeter", "syllables": ["cen", "ti", "me", "ter"], "ipa": "/ˈsentɪmiːtər/", "meaning": "n. 公分" },
    { "level": 5, "word": "colorful", "syllables": ["col", "or", "ful"], "ipa": "/ˈkʌlərf(ə)l/", "meaning": "adj. 多彩的" },
    { "level": 5, "word": "common", "syllables": ["com", "mon"], "ipa": "/ˈkɑːmən/", "meaning": "adj. 常見的" },
    { "level": 5, "word": "company", "syllables": ["com", "pa", "ny"], "ipa": "/ˈkʌmpəni/", "meaning": "n. 公司" },
    { "level": 5, "word": "convenient", "syllables": ["con", "ven", "ient"], "ipa": "/kənˈviːniənt/", "meaning": "adj. 便利的" },
    { "level": 5, "word": "conversation", "syllables": ["con", "ver", "sa", "tion"], "ipa": "/ˌkɑːnvərˈseɪʃn/", "meaning": "n. 對話" },
    { "level": 5, "word": "difficult", "syllables": ["dif", "fi", "cult"], "ipa": "/ˈdɪfɪkəlt/", "meaning": "adj. 困難的" },
    { "level": 5, "word": "dinosaur", "syllables": ["di", "no", "saur"], "ipa": "/ˈdaɪnəsɔːr/", "meaning": "n. 恐龍" },
    { "level": 5, "word": "excited", "syllables": ["ex", "cit", "ed"], "ipa": "/ɪkˈsaɪtɪd/", "meaning": "adj. 感到興奮的" },
    { "level": 5, "word": "famous", "syllables": ["fa", "mous"], "ipa": "/ˈfeɪməs/", "meaning": "adj. 有名的" },
    { "level": 5, "word": "festival", "syllables": ["fes", "ti", "val"], "ipa": "/ˈfestɪvl/", "meaning": "n. 節日" },
    { "level": 5, "word": "foreigner", "syllables": ["for", "eign", "er"], "ipa": "/ˈfɔːrənər/", "meaning": "n. 外國人" },
    { "level": 5, "word": "history", "syllables": ["his", "to", "ry"], "ipa": "/ˈhɪstri/", "meaning": "n. 歷史" },
    { "level": 5, "word": "introduce", "syllables": ["in", "tro", "duce"], "ipa": "/ˌɪntrəˈduːs/", "meaning": "v. 介紹" },
    { "level": 5, "word": "knowledge", "syllables": ["knowl", "edge"], "ipa": "/ˈnɑːlɪdʒ/", "meaning": "n. 知識" },
    { "level": 5, "word": "newspaper", "syllables": ["news", "pa", "per"], "ipa": "/ˈnuːzpeɪpər/", "meaning": "n. 報紙" },
    { "level": 5, "word": "photograph", "syllables": ["pho", "to", "graph"], "ipa": "/ˈfoʊtəɡræf/", "meaning": "n. 照片" },
    { "level": 5, "word": "popular", "syllables": ["pop", "u", "lar"], "ipa": "/ˈpɑːpjələr/", "meaning": "adj. 受歡迎的" },
    { "level": 5, "word": "serious", "syllables": ["se", "ri", "ous"], "ipa": "/ˈsɪriəs/", "meaning": "adj. 嚴肅的" },
    { "level": 5, "word": "vacation", "syllables": ["va", "ca", "tion"], "ipa": "/veɪˈkeɪʃn/", "meaning": "n. 假期" },

    // === Level 6 ===
    { "level": 6, "word": "baby", "syllables": ["ba", "by"], "ipa": "/ˈbeɪbi/", "meaning": "n. 嬰兒" },
    { "level": 6, "word": "back", "syllables": ["back"], "ipa": "/bæk/", "meaning": "n.adv. 背部；回來" },
    { "level": 6, "word": "bank", "syllables": ["bank"], "ipa": "/bæŋk/", "meaning": "n. 銀行" },
    { "level": 6, "word": "barbecue", "syllables": ["bar", "be", "cue"], "ipa": "/ˈbɑːrbɪkjuː/", "meaning": "n.v. 烤肉" },
    { "level": 6, "word": "basket", "syllables": ["bas", "ket"], "ipa": "/ˈbæskɪt/", "meaning": "n. 籃子" },
    { "level": 6, "word": "basketball", "syllables": ["bas", "ket", "ball"], "ipa": "/ˈbæskɪtbɔːl/", "meaning": "n. 籃球" },
    { "level": 6, "word": "bath", "syllables": ["bath"], "ipa": "/bæθ/", "meaning": "n. 洗澡" },
    { "level": 6, "word": "be", "syllables": ["be"], "ipa": "/biː/", "meaning": "v. 是" },
    { "level": 6, "word": "beach", "syllables": ["beach"], "ipa": "/biːtʃ/", "meaning": "n. 海灘" },
    { "level": 6, "word": "because", "syllables": ["be", "cause"], "ipa": "/bɪˈkɔːz/", "meaning": "conj. 因為" },
    { "level": 6, "word": "beer", "syllables": ["beer"], "ipa": "/bɪr/", "meaning": "n. 啤酒" },
    { "level": 6, "word": "before", "syllables": ["be", "fore"], "ipa": "/bɪˈfɔːr/", "meaning": "prep.conj. 在...之前" },
    { "level": 6, "word": "behind", "syllables": ["be", "hind"], "ipa": "/bɪˈhaɪnd/", "meaning": "prep. 在...後面" },
    { "level": 6, "word": "bike", "syllables": ["bike"], "ipa": "/baɪk/", "meaning": "n. 腳踏車" },
    { "level": 6, "word": "blood", "syllables": ["blood"], "ipa": "/blʌd/", "meaning": "n. 血液" },
    { "level": 6, "word": "board", "syllables": ["board"], "ipa": "/bɔːrd/", "meaning": "n. 板子" },
    { "level": 6, "word": "boat", "syllables": ["boat"], "ipa": "/boʊt/", "meaning": "n. 船" },
    { "level": 6, "word": "bookstore", "syllables": ["book", "store"], "ipa": "/ˈbʊkstɔːr/", "meaning": "n. 書店" },
    { "level": 6, "word": "boss", "syllables": ["boss"], "ipa": "/bɔːs/", "meaning": "n. 老闆" },
    { "level": 6, "word": "bread", "syllables": ["bread"], "ipa": "/bred/", "meaning": "n. 麵包" },
    { "level": 6, "word": "bright", "syllables": ["bright"], "ipa": "/braɪt/", "meaning": "adj. 明亮的" },
    { "level": 6, "word": "brush", "syllables": ["brush"], "ipa": "/brʌʃ/", "meaning": "v.n. 刷；刷子" },
    { "level": 6, "word": "build", "syllables": ["build"], "ipa": "/bɪld/", "meaning": "v. 建造" },
    { "level": 6, "word": "bun", "syllables": ["bun"], "ipa": "/bʌn/", "meaning": "n. 小圓麵包" },
    { "level": 6, "word": "burn", "syllables": ["burn"], "ipa": "/bɜːrn/", "meaning": "v. 燃燒" },
    { "level": 6, "word": "butter", "syllables": ["but", "ter"], "ipa": "/ˈbʌtər/", "meaning": "n. 奶油" },
    { "level": 6, "word": "buy", "syllables": ["buy"], "ipa": "/baɪ/", "meaning": "v. 買" },
    { "level": 6, "word": "by", "syllables": ["by"], "ipa": "/baɪ/", "meaning": "prep. 經由" },
    { "level": 6, "word": "collection", "syllables": ["col", "lec", "tion"], "ipa": "/kəˈlekʃn/", "meaning": "n. 收藏品" },
    { "level": 6, "word": "impossible", "syllables": ["im", "pos", "si", "ble"], "ipa": "/ɪmˈpɑːsəbl/", "meaning": "adj. 不可能的" },
    { "level": 6, "word": "strawberry", "syllables": ["straw", "ber", "ry"], "ipa": "/ˈstrɔːberi/", "meaning": "n. 草莓" },
    { "level": 6, "word": "volleyball", "syllables": ["vol", "ley", "ball"], "ipa": "/ˈvɑːlibɔːl/", "meaning": "n. 排球" },

    // === Level 7 ===
    { "level": 7, "word": "addition", "syllables": ["ad", "di", "tion"], "ipa": "/əˈdɪʃn/", "meaning": "n. 附加；加法" },
    { "level": 7, "word": "attention", "syllables": ["at", "ten", "tion"], "ipa": "/əˈtenʃn/", "meaning": "n. 注意力" },
    { "level": 7, "word": "childhood", "syllables": ["child", "hood"], "ipa": "/ˈtʃaɪldhʊd/", "meaning": "n. 童年" },
    { "level": 7, "word": "difficulty", "syllables": ["dif", "fi", "cul", "ty"], "ipa": "/ˈdɪfɪkəlti/", "meaning": "n. 困難" },
    { "level": 7, "word": "government", "syllables": ["gov", "ern", "ment"], "ipa": "/ˈɡʌvərnmənt/", "meaning": "n. 政府" },
    { "level": 7, "word": "information", "syllables": ["in", "for", "ma", "tion"], "ipa": "/ˌɪnfərˈmeɪʃn/", "meaning": "n. 資訊" },
    { "level": 7, "word": "international", "syllables": ["in", "ter", "na", "tion", "al"], "ipa": "/ˌɪntərˈnæʃnəl/", "meaning": "adj. 國際的" },
    { "level": 7, "word": "kindergarten", "syllables": ["kin", "der", "gar", "ten"], "ipa": "/ˈkɪndərɡɑːrtn/", "meaning": "n. 幼稚園" },
    { "level": 7, "word": "necessary", "syllables": ["nec", "es", "sar", "y"], "ipa": "/ˈnesəseri/", "meaning": "adj. 必要的" },
    { "level": 7, "word": "population", "syllables": ["pop", "u", "la", "tion"], "ipa": "/ˌpɑːpjuˈleɪʃn/", "meaning": "n. 人口" },
    { "level": 7, "word": "stationery", "syllables": ["sta", "tion", "er", "y"], "ipa": "/ˈsteɪʃəneri/", "meaning": "n. 文具" },

    // === Level 8 ===
    { "level": 8, "word": "ambulance", "syllables": ["am", "bu", "lance"], "ipa": "/ˈæmbjələns/", "meaning": "n. 救護車" },
    { "level": 8, "word": "appearance", "syllables": ["ap", "pear", "ance"], "ipa": "/əˈpɪrəns/", "meaning": "n. 外貌" },
    { "level": 8, "word": "appreciate", "syllables": ["ap", "pre", "ci", "ate"], "ipa": "/əˈpriːʃieɪt/", "meaning": "v. 感激" },
    { "level": 8, "word": "direction", "syllables": ["di", "rec", "tion"], "ipa": "/daɪˈrekʃn/", "meaning": "n. 方向" },
    { "level": 8, "word": "environment", "syllables": ["en", "vi", "ron", "ment"], "ipa": "/ɪnˈvaɪrənmənt/", "meaning": "n. 環境" },
    { "level": 8, "word": "opportunity", "syllables": ["op", "por", "tu", "ni", "ty"], "ipa": "/ˌɑːpərˈtuːnəti/", "meaning": "n. 機會" },
    { "level": 8, "word": "responsible", "syllables": ["re", "spon", "si", "ble"], "ipa": "/rɪˈspɑːnsəbl/", "meaning": "adj. 負責任的" },
    { "level": 8, "word": "temperature", "syllables": ["tem", "per", "a", "ture"], "ipa": "/ˈtemprətʃər/", "meaning": "n. 溫度" },
    { "level": 8, "word": "vocabulary", "syllables": ["vo", "cab", "u", "lar", "y"], "ipa": "/vəˈkæbjəleri/", "meaning": "n. 詞彙量" }
];
