// words.js - OPA-ABC 單字資料庫 (Level 1 & Level 2)
const allWords = [
    // === Level 1 ===
    { "level": 1, "word": "after", "syllables": ["af", "ter"], "ipa": "/ˈæftər/", "meaning": "prep.conj. 在...之後" },
    { "level": 1, "word": "afternoon", "syllables": ["af", "ter", "noon"], "ipa": "/ˌæftərˈnuːn/", "meaning": "n. 下午" },
    { "level": 1, "word": "apple", "syllables": ["ap", "ple"], "ipa": "/ˈæpl/", "meaning": "n. 蘋果" },
    { "level": 1, "word": "April", "syllables": ["A", "pril"], "ipa": "/ˈeɪprəl/", "meaning": "n. 四月" },
    { "level": 1, "word": "August", "syllables": ["Au", "gust"], "ipa": "/ɔːˈɡʌst/", "meaning": "n. 八月" },
    { "level": 1, "word": "banana", "syllables": ["ba", "nan", "a"], "ipa": "/bəˈnænə/", "meaning": "n. 香蕉" },
    { "level": 1, "word": "bathroom", "syllables": ["bath", "room"], "ipa": "/ˈbæθruːm/", "meaning": "n. 浴室" },
    { "level": 1, "word": "bedroom", "syllables": ["bed", "room"], "ipa": "/ˈbedruːm/", "meaning": "n. 臥室" },
    { "level": 1, "word": "bicycle", "syllables": ["bi", "cy", "cle"], "ipa": "/ˈbaɪsɪkl/", "meaning": "n. 腳踏車" },
    { "level": 1, "word": "birthday", "syllables": ["birth", "day"], "ipa": "/ˈbɜːrθdeɪ/", "meaning": "n. 生日" },
    { "level": 1, "word": "blackboard", "syllables": ["black", "board"], "ipa": "/ˈblækbɔːrd/", "meaning": "n. 黑板" },
    { "level": 1, "word": "brother", "syllables": ["broth", "er"], "ipa": "/ˈbrʌðər/", "meaning": "n. 兄弟" },
    { "level": 1, "word": "chicken", "syllables": ["chick", "en"], "ipa": "/ˈtʃɪkɪn/", "meaning": "n. 雞肉" },
    { "level": 1, "word": "chocolate", "syllables": ["choc", "o", "late"], "ipa": "/ˈtʃɑːklət/", "meaning": "n. 巧克力" },
    { "level": 1, "word": "computer", "syllables": ["com", "pu", "ter"], "ipa": "/kəmˈpjuːtər/", "meaning": "n. 電腦" },
    { "level": 1, "word": "December", "syllables": ["De", "cem", "ber"], "ipa": "/dɪˈsembər/", "meaning": "n. 十二月" },
    { "level": 1, "word": "dinner", "syllables": ["din", "ner"], "ipa": "/ˈdɪnər/", "meaning": "n. 晚餐" },
    { "level": 1, "word": "doctor", "syllables": ["doc", "tor"], "ipa": "/ˈdɑːktər/", "meaning": "n. 醫師" },
    { "level": 1, "word": "eighteen", "syllables": ["eigh", "teen"], "ipa": "/ˌeɪˈtiːn/", "meaning": "num. 十八" },
    { "level": 1, "word": "elephant", "syllables": ["el", "e", "phant"], "ipa": "/ˈelɪfənt/", "meaning": "n. 大象" },
    { "level": 1, "word": "English", "syllables": ["Eng", "lish"], "ipa": "/ˈɪŋɡlɪʃ/", "meaning": "adj.n. 英語" },
    { "level": 1, "word": "eraser", "syllables": ["e", "ras", "er"], "ipa": "/ɪˈreɪsər/", "meaning": "n. 擦布" },
    { "level": 1, "word": "evening", "syllables": ["e", "ve", "ning"], "ipa": "/ˈiːvnɪŋ/", "meaning": "n. 晚上" },
    { "level": 1, "word": "father", "syllables": ["fa", "ther"], "ipa": "/ˈfɑːðər/", "meaning": "n. 父親" },
    { "level": 1, "word": "February", "syllables": ["Feb", "ru", "ar", "y"], "ipa": "/ˈfebrueri/", "meaning": "n. 二月" },
    { "level": 1, "word": "fifteen", "syllables": ["fif", "teen"], "ipa": "/ˌfɪfˈtiːn/", "meaning": "num. 十五" },
    { "level": 1, "word": "flower", "syllables": ["flow", "er"], "ipa": "/ˈflaʊər/", "meaning": "n. 花朵" },
    { "level": 1, "word": "fourteen", "syllables": ["four", "teen"], "ipa": "/ˌfɔːrˈtiːn/", "meaning": "num. 十四" },
    { "level": 1, "word": "hamburger", "syllables": ["ham", "burg", "er"], "ipa": "/ˈhæmbɜːrɡər/", "meaning": "n. 漢堡" },
    { "level": 1, "word": "homework", "syllables": ["home", "work"], "ipa": "/ˈhoʊmwɜːrk/", "meaning": "n. 作業" },
    { "level": 1, "word": "jacket", "syllables": ["jack", "et"], "ipa": "/ˈdʒækɪt/", "meaning": "n. 夾克" },
    { "level": 1, "word": "January", "syllables": ["Jan", "u", "ar", "y"], "ipa": "/ˈdʒænjueri/", "meaning": "n. 一月" },
    { "level": 1, "word": "kitchen", "syllables": ["kit", "chen"], "ipa": "/ˈkɪtʃɪn/", "meaning": "n. 廚房" },
    { "level": 1, "word": "morning", "syllables": ["morn", "ing"], "ipa": "/ˈmɔːrnɪŋ/", "meaning": "n. 早晨" },
    { "level": 1, "word": "notebook", "syllables": ["note", "book"], "ipa": "/ˈnoʊtbʊk/", "meaning": "n. 筆記本" },
    { "level": 1, "word": "November", "syllables": ["No", "vem", "ber"], "ipa": "/noʊˈvembər/", "meaning": "n. 十一月" },
    { "level": 1, "word": "October", "syllables": ["Oc", "to", "ber"], "ipa": "/ɑːkˈtoʊbər/", "meaning": "n. 十月" },
    { "level": 1, "word": "sandwich", "syllables": ["sand", "wich"], "ipa": "/ˈsænwɪtʃ/", "meaning": "n. 三明治" },
    { "level": 1, "word": "Saturday", "syllables": ["Sat", "ur", "day"], "ipa": "/ˈsætərdeɪ/", "meaning": "n. 星期六" },
    { "level": 1, "word": "September", "syllables": ["Sep", "tem", "ber"], "ipa": "/sepˈtembər/", "meaning": "n. 九月" },
    { "level": 1, "word": "a", "syllables": ["a"], "ipa": "/ə/", "meaning": "art. 一個" },
    { "level": 1, "word": "ago", "syllables": ["a", "go"], "ipa": "/əˈɡoʊ/", "meaning": "adv. 以前" },
    { "level": 1, "word": "arm", "syllables": ["arm"], "ipa": "/ɑːrm/", "meaning": "n. 手臂" },
    { "level": 1, "word": "bad", "syllables": ["bad"], "ipa": "/bæd/", "meaning": "adj. 壞的" },
    { "level": 1, "word": "bag", "syllables": ["bag"], "ipa": "/bæɡ/", "meaning": "n. 袋子" },
    { "level": 1, "word": "ball", "syllables": ["ball"], "ipa": "/bɔːl/", "meaning": "n. 球" },
    { "level": 1, "word": "bear", "syllables": ["bear"], "ipa": "/ber/", "meaning": "n. 熊" },
    { "level": 1, "word": "bed", "syllables": ["bed"], "ipa": "/bed/", "meaning": "n. 床" },
    { "level": 1, "word": "bee", "syllables": ["bee"], "ipa": "/biː/", "meaning": "n. 蜜蜂" },
    { "level": 1, "word": "bell", "syllables": ["bell"], "ipa": "/bel/", "meaning": "n. 鐘" },
    { "level": 1, "word": "big", "syllables": ["big"], "ipa": "/bɪɡ/", "meaning": "adj. 大的" },
    { "level": 1, "word": "bird", "syllables": ["bird"], "ipa": "/bɜːrd/", "meaning": "n. 鳥" },
    { "level": 1, "word": "black", "syllables": ["black"], "ipa": "/blæk/", "meaning": "adj. 黑色的" },
    { "level": 1, "word": "blue", "syllables": ["blue"], "ipa": "/bluː/", "meaning": "adj.n. 藍色" },
    { "level": 1, "word": "body", "syllables": ["bod", "y"], "ipa": "/ˈbɑːdi/", "meaning": "n. 身體" },
    { "level": 1, "word": "book", "syllables": ["book"], "ipa": "/bʊk/", "meaning": "n. 書本" },
    { "level": 1, "word": "box", "syllables": ["box"], "ipa": "/bɑːks/", "meaning": "n. 盒子" },
    { "level": 1, "word": "boy", "syllables": ["boy"], "ipa": "/bɔɪ/", "meaning": "n. 男孩" },
    { "level": 1, "word": "brown", "syllables": ["brown"], "ipa": "/braʊn/", "meaning": "adj. 棕色的" },
    { "level": 1, "word": "bus", "syllables": ["bus"], "ipa": "/bʌs/", "meaning": "n. 公車" },
    { "level": 1, "word": "cake", "syllables": ["cake"], "ipa": "/keɪk/", "meaning": "n. 蛋糕" },
    { "level": 1, "word": "candy", "syllables": ["can", "dy"], "ipa": "/ˈkændi/", "meaning": "n. 糖果" },
    { "level": 1, "word": "car", "syllables": ["car"], "ipa": "/kɑːr/", "meaning": "n. 車子" },
    { "level": 1, "word": "cat", "syllables": ["cat"], "ipa": "/kæt/", "meaning": "n. 貓" },
    { "level": 1, "word": "chair", "syllables": ["chair"], "ipa": "/tʃer/", "meaning": "n. 椅子" },
    { "level": 1, "word": "clock", "syllables": ["clock"], "ipa": "/klɑːk/", "meaning": "n. 時鐘" },
    { "level": 1, "word": "coffee", "syllables": ["cof", "fee"], "ipa": "/ˈkɔːfi/", "meaning": "n. 咖啡" },
    { "level": 1, "word": "color", "syllables": ["col", "or"], "ipa": "/ˈkʌlər/", "meaning": "n. 顏色" },
    { "level": 1, "word": "cookie", "syllables": ["cook", "ie"], "ipa": "/ˈkʊki/", "meaning": "n. 餅乾" },
    { "level": 1, "word": "cup", "syllables": ["cup"], "ipa": "/kʌp/", "meaning": "n. 杯子" },
    { "level": 1, "word": "dad", "syllables": ["dad"], "ipa": "/dæd/", "meaning": "n. 爸爸" },
    { "level": 1, "word": "dance", "syllables": ["dance"], "ipa": "/dæns/", "meaning": "v. 跳舞" },
    { "level": 1, "word": "day", "syllables": ["day"], "ipa": "/deɪ/", "meaning": "n. 白天" },
    { "level": 1, "word": "desk", "syllables": ["desk"], "ipa": "/desk/", "meaning": "n. 書桌" },
    { "level": 1, "word": "dog", "syllables": ["dog"], "ipa": "/dɔːɡ/", "meaning": "n. 狗" },
    { "level": 1, "word": "doll", "syllables": ["doll"], "ipa": "/dɑːl/", "meaning": "n. 娃娃" },
    { "level": 1, "word": "door", "syllables": ["door"], "ipa": "/dɔːr/", "meaning": "n. 門" },
    { "level": 1, "word": "zoo", "syllables": ["zoo"], "ipa": "/zuː/", "meaning": "n. 動物園" },

    // === Level 2 ===
    { "level": 2, "word": "A.M.", "syllables": ["A.M."], "ipa": "/ˌeɪ ˈem/", "meaning": "abbr. 上午" },
    { "level": 2, "word": "about", "syllables": ["a", "bout"], "ipa": "/əˈbaʊt/", "meaning": "prep. 關於" },
    { "level": 2, "word": "again", "syllables": ["a", "gain"], "ipa": "/əˈɡen/", "meaning": "adv. 再次" },
    { "level": 2, "word": "age", "syllables": ["age"], "ipa": "/eɪdʒ/", "meaning": "n. 年齡" },
    { "level": 2, "word": "airplane", "syllables": ["air", "plane"], "ipa": "/ˈerpleɪn/", "meaning": "n. 飛機" },
    { "level": 2, "word": "airport", "syllables": ["air", "port"], "ipa": "/ˈerpɔːrt/", "meaning": "n. 機場" },
    { "level": 2, "word": "all", "syllables": ["all"], "ipa": "/ɔːl/", "meaning": "adj. 全部" },
    { "level": 2, "word": "animal", "syllables": ["an", "i", "mal"], "ipa": "/ˈænɪml/", "meaning": "n. 動物" },
    { "level": 2, "word": "answer", "syllables": ["an", "swer"], "ipa": "/ˈænsər/", "meaning": "n.v. 答案" },
    { "level": 2, "word": "anybody", "syllables": ["an", "y", "bod", "y"], "ipa": "/ˈenibɑːdi/", "meaning": "pron. 任何人" },
    { "level": 2, "word": "autumn", "syllables": ["au", "tumn"], "ipa": "/ˈɔːtəm/", "meaning": "n. 秋天" },
    { "level": 2, "word": "bakery", "syllables": ["bak", "er", "y"], "ipa": "/ˈbeɪkəri/", "meaning": "n. 麵包店" },
    { "level": 2, "word": "baseball", "syllables": ["base", "ball"], "ipa": "/ˈbeɪsbɔːl/", "meaning": "n. 棒球" },
    { "level": 2, "word": "beautiful", "syllables": ["beau", "ti", "ful"], "ipa": "/ˈbjuːtɪfl/", "meaning": "adj. 美麗的" },
    { "level": 2, "word": "between", "syllables": ["be", "tween"], "ipa": "/bɪˈtwiːn/", "meaning": "prep. 在...之間" },
    { "level": 2, "word": "cheese", "syllables": ["cheese"], "ipa": "/tʃiːz/", "meaning": "n. 乳酪" },
    { "level": 2, "word": "circle", "syllables": ["cir", "cle"], "ipa": "/ˈsɜːrkl/", "meaning": "n. 圓圈" },
    { "level": 2, "word": "daughter", "syllables": ["daugh", "ter"], "ipa": "/ˈdɔːtər/", "meaning": "n. 女兒" },
    { "level": 2, "word": "everyone", "syllables": ["ev", "er", "y", "one"], "ipa": "/ˈevriwʌn/", "meaning": "pron. 每個人" },
    { "level": 2, "word": "exercise", "syllables": ["ex", "er", "cise"], "ipa": "/ˈeksərsaɪz/", "meaning": "n.v. 運動" },
    { "level": 2, "word": "favorite", "syllables": ["fa", "vor", "ite"], "ipa": "/ˈfeɪvərɪt/", "meaning": "adj.n. 最喜愛的" },
    { "level": 2, "word": "grandfather", "syllables": ["grand", "fa", "ther"], "ipa": "/ˈɡrænfɑːðər/", "meaning": "n. 祖父" },
    { "level": 2, "word": "hospital", "syllables": ["hos", "pi", "tal"], "ipa": "/ˈhɑːspɪtl/", "meaning": "n. 醫院" },
    { "level": 2, "word": "hundred", "syllables": ["hun", "dred"], "ipa": "/ˈhʌndrəd/", "meaning": "num. 一百" },
    { "level": 2, "word": "listen", "syllables": ["lis", "ten"], "ipa": "/ˈlɪsn/", "meaning": "v. 聽" },
    { "level": 2, "word": "marker", "syllables": ["mark", "er"], "ipa": "/ˈmɑːrkər/", "meaning": "n. 麥克筆" },
    { "level": 2, "word": "medicine", "syllables": ["med", "i", "cine"], "ipa": "/ˈmedsn/", "meaning": "n. 藥物" },
    { "level": 2, "word": "museum", "syllables": ["mu", "se", "um"], "ipa": "/mjuˈziːəm/", "meaning": "n. 博物館" },
    { "level": 2, "word": "often", "syllables": ["of", "ten"], "ipa": "/ˈɔːfn/", "meaning": "adv. 經常" },
    { "level": 2, "word": "playground", "syllables": ["play", "ground"], "ipa": "/ˈpleɪɡraʊnd/", "meaning": "n. 遊樂場" },
    { "level": 2, "word": "question", "syllables": ["ques", "tion"], "ipa": "/ˈkwestʃən/", "meaning": "n. 問題" },
    { "level": 2, "word": "quiet", "syllables": ["qui", "et"], "ipa": "/ˈkwaɪət/", "meaning": "adj. 安靜的" },
    { "level": 2, "word": "remember", "syllables": ["re", "mem", "ber"], "ipa": "/rɪˈmembər/", "meaning": "v. 記得" },
    { "level": 2, "word": "restaurant", "syllables": ["res", "tau", "rant"], "ipa": "/ˈrestrɑːnt/", "meaning": "n. 餐廳" },
    { "level": 2, "word": "sentence", "syllables": ["sen", "tence"], "ipa": "/ˈsentəns/", "meaning": "n. 句子" },
    { "level": 2, "word": "sometimes", "syllables": ["some", "times"], "ipa": "/ˈsʌmtaɪmz/", "meaning": "adv. 有時候" },
    { "level": 2, "word": "together", "syllables": ["to", "geth", "er"], "ipa": "/təˈɡeðər/", "meaning": "adv. 一起" },
    { "level": 2, "word": "vegetable", "syllables": ["veg", "e", "ta", "ble"], "ipa": "/ˈvedʒtəbl/", "meaning": "n. 蔬菜" },
    { "level": 2, "word": "yesterday", "syllables": ["yes", "ter", "day"], "ipa": "/ˈjestərdeɪ/", "meaning": "n. 昨天" }
];